### ISSUE TITLE
Jumphost not respecting server connection

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#100]
When using the memfd injection function, everything works fine using `connect --shell rssh://filename id` after connecting to rssh.

 But an error occurs when using `ssh -J ip:port id rssh://filename`

error: `ssh rejected: administratively prohibited`

**Comment by NHAS** [comment]
Huh thats odd, it definitely should work.

**Comment by NHAS** [comment]
Thanks for this, definitely a bug

**Comment by NHAS** [comment]
This is on unstable branch now
