### ISSUE TITLE
garble amd64

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#102]
Hi, I used to link --garble all the time but now it doesn't work for amd64, it won't create anything and the server is the same, nothing has been changed. If I put a 386, then --garble works.

link -C test --goos windows --goarch amd64 --name test --garble

Here is the error:

Error: exit status 1
# golang.org/x/crypto/blowfish
cannot load garble export file for errors: open /root/.cache/go-build/d6/d63ebd7edae8d891cb05785d643427cba85462f4f2f503dde294258634517f05-garble-4Zb0hs6GfTKva35I3OmT-d: no such file or directory
# golang.org/x/crypto/ed25519
cannot load garble export file for bytes: open /root/.cache/go-build/f8/f8968f7a2ce9bff4ac1f69f25f542c6d420fe7cb0604ad72b2c845e9dba4cae9-garble-byWwglD7eB6qPAQD6uDC-d: no such file or directory
# golang.org/x/crypto/chacha20
cannot load garble export file for crypto/cipher: open /root/.cache/go-build/1d/1dfca4ae163fc08e2fb427291551ee6f2f1d10cd03020be933f74f1f5dd6a047-garble-KgdGxSFZfbHl9DwYuwua-d: no such file or directory
# github.com/Azure/go-ansiterm
cannot load garble export file for errors: open /root/.cache/go-build/d6/d63ebd7edae8d891cb05785d643427cba85462f4f2f503dde294258634517f05-garble-4Zb0hs6GfTKva35I3OmT-d: no such file or directory
# golang.org/x/crypto/internal/poly1305
cannot load garble export file for crypto/subtle: open /root/.cache/go-build/0e/0ee81fe0b748face53f6a4d169923420543a583ee72e4cbdfe7e7c927ec891ec-garble-zGX1QSqstIczsARF4ZfK-d: no such file or directory
# golang.org/x/crypto/curve25519/internal/field
cannot load garble export file for crypto/subtle: open /root/.cache/go-build/0e/0ee81fe0b748face53f6a4d169923420543a583ee72e4cbdfe7e7c927ec891ec-garble-zGX1QSqstIczsARF4ZfK-d: no such file or directory
# golang.org/x/sys/windows
cannot load garble export file for bytes: open /root/.cache/go-build/f8/f8968f7a2ce9bff4ac1f69f25f542c6d420fe7cb0604ad72b2c845e9dba4cae9-garble-byWwglD7eB6qPAQD6uDC-d: no such file or directory
exit status 2

But the 386, everything works fine.

catcher$ link -C test --goos windows --goarch 386 --name test --garble 

http://IP:PORT/test

It's the version of garble you recommended.

**Comment by chikamobina** [comment]
garble version
mvdan.cc/garble v0.7.2-0.20220906164632-f9d99190d29e

**Comment by chikamobina** [comment]
rm -rf /root/.cache/go-build/* and it worked.)

**Comment by NHAS** [comment]
Glad you managed to solve it. Thanks for putting the solution here. I've been quite busy with work at the moment.

Sorry!
