### ISSUE TITLE
Auto reconnect fails

### ISSUE THREAD

**Issue by Ari-Weinberg** [NHAS/reverse_ssh#104]
Is there a way to implement some sort of auto reconnect for the client? I'm finding that the client sometimes loses the connection to the jump server, but the process is still alive when I re connect with another process. It would be awesome if the client would sense that the connection is lost, and re-connect.

**Comment by Ari-Weinberg** [comment]
Sure. I'm doing a Hack The Box lab, and I've deployed the client to a machine. That machine seems to have a spotty connection, and so the client keeps disconnecting. when I start a new client process, or use `ps aux` through the command injection vuln that got me in in the first place, it shows the original client processes are still active (`/proc/self/exe --foreground <IP>:<PORT>`).
If it changes anything, the victim that the client runs on is a docker container, but I dont think that should make a difference.

**Comment by Ari-Weinberg** [comment]
It doesn't come back at all. 
I cant find a version number, but Im pretty sure I downloaded Dec 22 2023
How would I get the logs?

**Comment by NHAS** [comment]
You can find the version by using the `version` command.

You should try using the latest version just in case. I did make some changes regarding some out and reconnection in 1.0.15

**Comment by NHAS** [comment]
Unless I get some more information/logs on this Im going to close the issue. If you want, feel free to open it again. Or I may open it if I have similar issues :)
