### ISSUE TITLE
Version cannot be checked

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#105]
Hi, thank you very much for your answer and help on the issue I submitted before. Based on your reverse SSH tunnel, I open sourced a remote control management project based on the web platform. You are welcome to test and use it and make suggestions. 

[https://github.com/tdragon6/Supershell](https://github.com/tdragon6/Supershell)

For v1.0.16, there seem to be two problems: 

1. There will still be the same error for the issue #100.
2. After connecting to the rssh service, the return result of the **version** command is empty, and the version of the rssh server cannot be checked.

It would be great if the above two issues can be fixed together in the next version release!

**Comment by NHAS** [comment]
Hey there! 

That looks really cool, thanks for making it. A few questions, why does your github repo not actually contain any source code for your application? 


And Im not sure what you mean by issue #100 being still around, I've fixed that unless you've found different?

**Comment by NHAS** [comment]
I've just pushed a minor change to unstable. See if that works for ya

**Comment by tdragon6** [comment]
Because the sub-repo of your reverse_ssh is referenced in my code, it is inconvenient to submit and manage in my repo, so I package all the codes into release for distribution.

As for the #100 issue, I still found this error when I tested it last time.

**ssh rejected: administratively prohibited**

I'll verify it again later when I'm free and get the details back to you，thanks！

**Comment by NHAS** [comment]
Thats a shame, I am unwilling to run a precompiled binary with no source on my computer.

**Comment by tdragon6** [comment]
The release is not a binary file, it is all source code, but it is packed in a compressed package.

**Comment by tdragon6** [comment]
Sorry, I may have got the version wrong earlier, issue #100 has been fixed.

But it seems that the `version` command still cannot echo the version information, as shown in the figure below:

<img width="238" alt="version" src="https://user-images.githubusercontent.com/95691624/228859054-36756ee4-8abf-4b15-a8ed-68189ffed030.png">

**Comment by tdragon6** [comment]
You reminded me, when I use `make` to compile everything is normal, when I use `make server` to compile, there is a problem.

After checking the makefile, I found that the `server` tag did not add the LDFLAGS flag which contains version info.

I would like to ask if there should be no difference between `make` and `make server` except for the version problem, the generation of the secret key and the compilation of the client file, right?

Also, I think the LDFLAGS flag can be added to the `server` tag in the makefile.

**Comment by NHAS** [comment]
Ahhhh right you are. Good spot, I've just updated that for you, on unstable :)
