### ISSUE TITLE
Customization of client process name

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#108]
Can the name of the child process after the client fork be customized in linux?

The current process name is `exe` , which is more obvious.

`tcp 0 0 10.0.4.2:43574 X.X.X.X:3232 ESTABLISHED 17763/exe`

**Comment by NHAS** [comment]
That use to be a feature that I removed. I can look at adding it again at some point :)

**Comment by tdragon6** [comment]
Looking forward to seeing it in the next version!：)

**Comment by tdragon6** [comment]
Yes. I understand that.

**Comment by NHAS** [comment]
Sorry for the delay, this is now on unstable
