### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by StevenKSaint** [NHAS/reverse_ssh#109]
Hello, I reported an error during the manual installation, is it because of my network?
```
internal/client/handlers/shell.go:18:2: github.com/creack/pty@v1.1.18: Get "https://proxy.golang.org/github.com/creack/pty/@v/v1.1.18.zip": dial tcp 172.217.160.81:443: i/o timeout
pkg/storage/store_linux.go:7:2: github.com/justincormack/go-memfd@v0.0.0-20170219213707-6e4af0518993: Get "https://proxy.golang.org/github.com/justincormack/go-memfd/@v/v0.0.0-20170219213707-6e4af0518993.zip": dial tcp 172.217.160.81:443: i/o timeout
internal/client/handlers/subsystems/sftp.go:8:2: github.com/pkg/sftp@v1.13.5: Get "https://proxy.golang.org/github.com/pkg/sftp/@v/v1.13.5.zip": dial tcp 172.217.160.81:443: i/o timeout
internal/global.go:17:2: golang.org/x/crypto@v0.7.0: Get "https://proxy.golang.org/golang.org/x/crypto/@v/v0.7.0.zip": dial tcp 172.217.160.81:443: i/o timeout
make: *** [Makefile:23: debug] Error 1
```

**Comment by NHAS** [comment]
Howdy,

That does look like a network issue on your side. Or the golang public package Proxy is down.

**Comment by StevenKSaint** [comment]
Using the following command to install also reported an error, what is the reason?
docker run -p9999:2222 -e EXTERNAL_ADDRESS=47.1**.***.**:9999 -e SEED_AUTHORIZED_KEYS="$(cat ~/.ssh/id_ed25519.pub)" -v data:/data reversessh/reverse_ssh
cat: /root/.ssh/id_ed25519.pub: No such file or directory
2023/04/14 16:35:31 Loading files from /data
2023/04/14 16:35:31 Version:  
2023/04/14 16:35:31 Listening on :2222
2023/04/14 16:35:31 Loading private key from: /data/id_ed25519
2023/04/14 16:35:31 Server key fingerprint:  9a8a22a78c02598f7afa6890bd27b1371d6ba9cb7f1ab5880c66b8eac4202ef6
2023/04/14 16:35:31 Loading authorized keys from: /data/authorized_keys
2023/04/14 16:35:31 Was unable to read webhooks configuration file
2023/04/14 16:35:31 Created downloads directory
2023/04/14 16:35:31 Unable to load cache:  open /data/cache/description.json: no such file or directory
2023/04/14 16:35:31 Started Web Server

**Comment by NHAS** [comment]
Those are just earnings rather than complete failures. If it was an error it wouldn't start.

Those are just saying that there have been no binaries generated with the `link` command, and no webhooks have been registered
