### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by StevenKSaint** [NHAS/reverse_ssh#110]
touch bin/authorized_controllee_keys
go build -ldflags="-X 'github.com/NHAS/reverse_ssh/internal.Version=v1.0.17'" -o bin ./...
build golang.org/x/sys/windows/svc/eventlog: cannot load golang.org/x/sys/windows/svc/eventlog: no Go source files
make: *** [Makefile:23: debug] Error 1

**Comment by NHAS** [comment]
Hi there, 

I am not able to replicate this. What platform are you building this on? And what version of golang are you on?

**Comment by CloudStrifer** [comment]
你是傻逼 @StevenKSaint
