### ISSUE TITLE
macOS - exec request failed on channel 1

### ISSUE THREAD

**Issue by vngvng** [NHAS/reverse_ssh#111]
Hi

May I know how can I ssh from macOS?
When connecting to the server by macOS terminal, it prompt
exec request failed on channel 1

I have tested in linux and it works.
Thanks.

**Comment by NHAS** [comment]
Can you give me the command you ran to get this?

I have never had this happen and I run this off of mac

**Comment by NHAS** [comment]
You may need to give me your rssh server logs to help diagnose this issue. I believe this will be something wrong with how you've configured ssh to connect to your server.

**Comment by vngvng** [comment]
I use the docker version on arm64, please let me know where the logs should get.

**Comment by NHAS** [comment]
Just the docker logs of the rssh server container will do fine

**Comment by NHAS** [comment]
Hi there, as I cant replicate this issue (the permission denied issue) and the original problem was due to using warp. 

Im going to close this issue. 
If you have any other bugs, please feel free to open a new issue.

**Comment by vngvng** [comment]
I re-build the container and the issue was gone, Thanks~!
