### ISSUE TITLE
大小

### ISSUE THREAD

**Issue by xiaoxiaoranxxx** [NHAS/reverse_ssh#112]
客户端能不能做出精简版的,只有shell连接的功能,,能够大大减小他的大小,能够达到2M左右

**Comment by NHAS** [comment]
你好，我不会说中文。
RSSH 不支持仅作为 SSH shell，这会更小，但我希望该项目具有 OpenSSH 守护程序的所有功能

**Comment by xiaoxiaoranxxx** [comment]
Thank you for your reply, I understand, my idea is similar to

https://github.com/Mob2003/rakshasa this, he has full and lite

**Comment by NHAS** [comment]
Yep, I mean I can always make a shell-only version of rssh and just see how it goes.

**Comment by shanjunmei** [comment]
1.go build -ldflags "-s -w" 
2.strip 去除可执行程序和动态库中的的符号和调试信息（这个好像可以进一步减少，相比于第一步的操作）
3.upx 简单压缩没负面作用，如果尝试提升压缩等级可能被报毒

**Comment by NHAS** [comment]
I think as I havent gotten around to this Im going to close it as unplanned. Sorry! As ShanJunmei has pointed out it is possible to shrink the binary quite a bit with UPX and stripping.
