### ISSUE TITLE
How can I use golang to connect to the target server？

### ISSUE THREAD

**Issue by sukabuliet** [NHAS/reverse_ssh#113]
I found that supershell uses "direct-tcpip" to establish a channel to connect to the target server, but I didn't find a similar method in golang's ssh, how can I solve it?

**Comment by NHAS** [comment]
Hi there, 

I would suggest reading up on how SSH works, and viewing example code within supershell and RSSH. 
If you have any RSSH specific questions, feature requests, or bugs I can help with those.
