### ISSUE TITLE
How to update the version if I use docker?

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#119]
Hi, please tell me how I can use the new version if I am using docker?

**Comment by NHAS** [comment]
Do you mean the version on unstable, or specifically the new version that I've just release.

Generally it should be just:
 `docker image pull reversessh/reverse_ssh`

Then re running it with the:

`docker run -p3232:2222 -e EXTERNAL_ADDRESS=<your_external_address>:3232 -e SEED_AUTHORIZED_KEYS="$(cat ~/.ssh/id_ed25519.pub)" -v data:/data reversessh/reverse_ssh`

**Comment by chikamobina** [comment]
docker image pull reversessh/reverse_ssh:latest Yes I needed that, thank you !
