### ISSUE TITLE
Running `link` with garble multiple times for windows fails

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#122]
By the way, there is also a little bug. After long use of link together with --garble, it starts giving this error. If docker is used then it gets solved by restarting, if just running ./server then deleting /root/.cache/ folder gets solved. I think it happens after you generate a few links with the same name in --name, delete and create new links with the same name and then you get this error.
github.com/NHAS/reverse_ssh/cmd/client

/root/.cache/garble/tool/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/bin/x86_64-w64-mingw32-ld: /tmp/go-link-1267569125/go.o:(.text+0x102cd2): undefined reference to `uJbRMLTAt.hZN1BXUE5YOj'
collect2: error: ld returned 1 exit status

exit status 2
exit status 1

**Comment by NHAS** [comment]
Thanks for this I'll see if I can replicate. Just working on re-adding the VPN (udp,tcp,icmp tunneling) back to rssh at user request :)

**Comment by NHAS** [comment]
Hmm I cant replicate this on either windows or linux with thew following flow:

```
catcher$ ls
No RSSH clients connected
catcher$ link --garble --name a
http://192.168.122.1:443/a
catcher$ link --garble --name b
http://192.168.122.1:443/b
catcher$ link --garble --name c
this link name is already in use
catcher$ link --garble --name d
this link name is already in use
catcher$ link --garble --name e
http://192.168.122.1:443/e
catcher$ link -r *
Removed 783fb1c2e38c4534af9ffdafd622e184
Removed c
Removed d
Removed a
Removed b
Removed e
catcher$ link --name a --garble
http://192.168.122.1:443/a
catcher$ link --name a --garble
this link name is already in use
catcher$ link --name b --garble
http://192.168.122.1:443/b
catcher$ link --name c --garble
http://192.168.122.1:443/c
catcher$ link --name d --garble
http://192.168.122.1:443/d
catcher$ link -r *
Removed a
Removed b
Removed c
Removed d
catcher$ link --name a --garble
http://192.168.122.1:443/a
catcher$ link --garble --name windows --goos windows
http://192.168.122.1:443/windows
catcher$ link --garble --name windows --goos windowslink -r *
Removed windows
Removed a
catcher$ link --garble --name windows --goos windows
http://192.168.122.1:443/windows
catcher$ link --garble --name windows --goos windows
this link name is already in use
catcher$ link -r *
Removed windows
catcher$ link --garble --name windows --goos windows
http://192.168.122.1:443/windows
```

**Comment by NHAS** [comment]
So may need more details around reproducing it

**Comment by chikamobina** [comment]
Тогда я не знаю как получается данная проблема, но она была у меня уже раз 7-8 за все время использования. У меня чистые разные сервера ubuntu, а rssh запускаю через docker.

**Comment by NHAS** [comment]
I take it this is very long running servers, I only let mine run for an hour or so after deleting a link and rebuilding using the same name. 

Super frustrating issue to have

**Comment by chikamobina** [comment]
Yes, this happens after 2-4 weeks of server operation. Resolved by clearing the cache or restarting docker

**Comment by chikamobina** [comment]
Hi, version 2.2.3 

catcher$ link -C test --goarch amd64 --garble --shared-object --goos windows                 
Error: exit status 1
# github.com/NHAS/reverse_ssh/cmd/client
/root/.cache/garble/tool/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/bin/x86_64-w64-mingw32-ld: /tmp/go-link-1426867729/go.o:(.text+0x27d7b2): undefined reference to `cwZ7KfYHOpmc.rlKNVGjp'
collect2: error: ld returned 1 exit status

exit status 2
exit status 1

**Comment by NHAS** [comment]
Right, thats super fucking annoying. Im going to do a work around that detects this issue and deletes `/root/.cache`

**Comment by NHAS** [comment]
Please give this a try on unstable and once you've confirmed it at least doesnt break I'll do a release

**Comment by chikamobina** [comment]
Ok

**Comment by chikamobina** [comment]
How can I install a non-stable version via Docker?

**Comment by NHAS** [comment]
`docker exec -it /bin/bash <server container id>`

Then do `git pull`, `git checkout unstable`, and then `make`

You'll need to restart the container to use the new server binary
