### ISSUE TITLE
link --name documentation is unintuitive

### ISSUE THREAD

**Issue by TheraNinjaCat** [NHAS/reverse_ssh#126]
I was initially unsure if it was possible to change the filename of the client as downloaded from link, and while in retrospect "Set link name" makes sense, I think it could be improved by making it clearer that this is specifically the filename of the client download. Potentially something along the lines of "Set the link download filename (default to random characters)" would be clearer.

**Comment by NHAS** [comment]
Yeah fair dinkum. I'll add that and pop it on unstable.
