### ISSUE TITLE
Problems with protocol judgement

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#127]
https://github.com/NHAS/reverse_ssh/blob/6c8654e9fe48b65041cc6722402207349989a9cd/pkg/mux/multiplexer.go#L212

The code protocol only gets the first three bytes, which means that all http requests will be misjudged except for GET and PUT methods, e.g. POST has four bytes

**Comment by NHAS** [comment]
Yep definitely an oversight. Thanks!
