### ISSUE TITLE
Use http_proxy / https_proxy environment variables automatically on clients

### ISSUE THREAD

**Issue by dwbzn** [NHAS/reverse_ssh#130]
RSSH can't connect back sometimes if the client relies on a proxy to get outbound access, and it's hard to know where to point --proxy unless you already know where the proxy is. 

This should be auto-used from the client's http_proxy / https_proxy environment variables : )

**Comment by NHAS** [comment]
I can definitely tie this is to the CONNECT proxy code, just gotta work out how to make sure doing magic automation doesnt turn into "incomprehensible bullshit"
