### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#132]
Hi, I start docker with the new version, works for a while and everything crashes with this error, and on all absolutely all servers and ports, the same problem. It happens after about a few hours of rssh, in idle mode. And the servers are clean completely, there is not even a single rssh client.

2023/09/12 22:20:37 [7.155.247.227:56866] INFO Web Server got hit:  /echo.php
2023/09/12 22:46:35 Multiplexing failed:  tls
2023/09/12 23:36:30 Multiplexing failed:  tls
2023/09/12 23:36:30 Multiplexing failed:  tls
2023/09/13 00:37:55 Multiplexing failed:  tls
2023/09/13 00:37:55 Multiplexing failed:  tls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7490f3]

goroutine 60 [running]:
github.com/NHAS/reverse_ssh/pkg/mux.ListenWithConfig.func1.1({0x914aa8, 0xc000230030})
        github.com/NHAS/reverse_ssh/pkg/mux/multiplexer.go:270 +0x8b3
created by github.com/NHAS/reverse_ssh/pkg/mux.ListenWithConfig.func1
        github.com/NHAS/reverse_ssh/pkg/mux/multiplexer.go:211 +0x14d

**Comment by NHAS** [comment]
Ugh those are words I never want to hear "Happens after a few hours"

**Comment by NHAS** [comment]
Just in general terms, how many clients would this have connected? None or heaps?

**Comment by chikamobina** [comment]
2023/09/12 20:39:10 [204.185.31.177:57700] INFO Web Server got hit:  /
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7490f3]

goroutine 30 [running]:
github.com/NHAS/reverse_ssh/pkg/mux.ListenWithConfig.func1.1({0x914aa8, 0xc000228058})
        github.com/NHAS/reverse_ssh/pkg/mux/multiplexer.go:270 +0x8b3
created by github.com/NHAS/reverse_ssh/pkg/mux.ListenWithConfig.func1
        github.com/NHAS/reverse_ssh/pkg/mux/multiplexer.go:211 +0x14d

Here's the output from the second server

**Comment by chikamobina** [comment]
> 

0

**Comment by NHAS** [comment]
Okay cool, so its just dying from a nil conn by the looks of things. Not sure how we could be getting nil there is the only problem. Hmmm

**Comment by NHAS** [comment]
Ah actually I do know why this might be happening

**Comment by chikamobina** [comment]
I took 2 servers, put ubuntu, ran rssh through docker, on 443 and 500 port, leave for a while and it crashes with this error. It's already 5 times like this, stable.

**Comment by chikamobina** [comment]
It's just that with the latest version only. There are no clients hanging on rssh, but when they were on the old server, there was exactly the same error

**Comment by NHAS** [comment]
Yep. So whats happening is with the new `determineProtocol` handler in the multiplexer, I've had to do some work so we now support websockets and tls. 

In rare circumstances:

```go
	header := make([]byte, 7)
	n, err := conn.Read(header)
	if err != nil {
		return nil, "failed: " + err.Error()
	}
```

This can cause a nil connection to be returned and this was not checked. Let me push a new version, I believe this should solve your issue.

**Comment by chikamobina** [comment]
Thank you.

**Comment by NHAS** [comment]
While this has been marked closed, this is my best guess at whats causing the problem (and really the only way that a nil connection could be getting to that point). 

If you're still having these issues, feel free to reopen and give me some more stack traces.

**Comment by chikamobina** [comment]
All right.

**Comment by NHAS** [comment]
Side note, you can now use rssh via cloudflare with its new websockets ability (so hopefully that makes up for this little crash :P)

**Comment by JSmith-Aura** [comment]
Howdy, can I get confirmation this patch has resolved the issue?
