### ISSUE TITLE
How can I use tls and wss

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#133]
I want to use tls or wss to encapsulate the channel when link or executing on the client. How do I use it and how do I specify the certificate?

Now I add the parameter --tls when link or add tls://ip:port to the -d parameter when executing on the client, but it doesn't seem to work.

**Comment by NHAS** [comment]
You need to enable `--tls` on the server side  for the `tls://` or `wss://` handlers to work. 

```
  Network
        --tls           Enable TLS on socket (ssh/http over TLS)
        --tlscert               TLS certificate path
        --tlskey                TLS key path
```

You can use plain `ws://` without enabling tls.

**Comment by NHAS** [comment]
It will automatically generate a cert for you. It wont be a valid cert, but it will be enough to let tls happen.
