### ISSUE TITLE
Webserver disconnects when downloading more than 10MB client

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#136]
When I open the webserver and use `link` to compile and generate the client, if I use garble obfuscation but do not use upx compression, the size of the client will often exceed 10MB. At this time, I found that when downloading using the url provided by the webserver, when the download cache exceeds 10MB, the webserver will disconnect, causing the download to fail.

This is the command I used to generate the client. 
`link --name mac --goos darwin --goarch amd64 --garble`

Its size is 12.6MB. I don’t know if this problem can be reproduced in your case.

**Comment by NHAS** [comment]
Howdy, can you give me some more details around this? 

What version are you testing this on? (assuming 2.2.2)
Are you using the tls handler?

**Comment by NHAS** [comment]
Yeah I cant replicate this locally, so Im going to have to know more about your set up. Do you use a reverse proxy?

**Comment by tdragon6** [comment]
I use docker to deploy rssh, and the version is 2.2.2. I'm not using any proxy. I’m not sure if it’s because of a problem with the deployed server. I tried switching to different networks, but I couldn’t download the client completely.

The impact of this problem is not big now. If you cannot reproduce this problem now, I will come across more valuable information in the future and raise an issue for reference.

**Comment by NHAS** [comment]
I've bumped the webserver io timeouts in the most recent release. I dont expect that to fix your problem entirely but its something. 

I havent had this happen for anyone else, so if you have more info on it I'd be happy to fix it if it is a problem. (nothing in the code that I can obviously see limits download size)
