### ISSUE TITLE
Remote ssh forwarding fails [ssh: rejected: administratively prohibited]

### ISSUE THREAD

**Issue by itschesko** [NHAS/reverse_ssh#137]
Really awesome tool, been using it for a while, recently I've noticed a problem: didn't need that feature for quite a while, last time I used it was February-March 2023 I believe and `-R` worked as expected. However, I updated since then and when I tried to forward port, I get the following message when trying to connect to a forwarded port `curl http://localhost:[PORT]`:

`WARNING: Server requests forwarding for unknown listen_port 1329`

Did a little research with baked/non-baked home address and both on linux and windows RSSH clients all the same, here's the log output from client:

```
2023/09/19 20:24:12 Connecting to  192.168.0.5:443
2023/09/19 20:24:13 Successfully connnected 192.168.0.5:443
2023/09/19 20:27:37 [client] INFO global.go:118 RegisterChannelCallbacks() : Handling channel: jump
2023/09/19 20:27:39 [192.168.0.5:443] INFO jumphost.go:52 func1() : New SSH connection, version SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.3
2023/09/19 20:27:39 [192.168.0.5:443] INFO global.go:118 RegisterChannelCallbacks() : Handling channel: session
2023/09/19 20:27:39 Started listening on:  127.0.0.1:15151
2023/09/19 20:27:40 [192.168.0.5:443] INFO session.go:57 Session() : Session got request: "pty-req"
2023/09/19 20:27:40 [192.168.0.5:443] INFO session.go:57 Session() : Session got request: "env"
2023/09/19 20:27:40 [192.168.0.5:443] WARNING session.go:150 Session() : Got an unknown request env
2023/09/19 20:27:40 [192.168.0.5:443] INFO session.go:57 Session() : Session got request: "env"
2023/09/19 20:27:40 [192.168.0.5:443] WARNING session.go:150 Session() : Got an unknown request env
2023/09/19 20:27:40 [192.168.0.5:443] INFO session.go:57 Session() : Session got request: "shell"
2023/09/19 20:27:40 [192.168.0.5:443] INFO shell_windows.go:132 runWithConpty() : New process with pid 19588 spawned
2023/09/19 20:27:48 Accepted new connection:  127.0.0.1:1329
2023/09/19 20:27:48 Opening forwarded-tcpip channel to server failed:  ssh: rejected: administratively prohibited (open failed)
2023/09/19 20:29:27 Server disconnected unexpectedly: connection terminated
2023/09/19 20:29:27 [client] ERROR jumphost.go:97 func1() : Channel call back error: connection terminated
2023/09/19 20:29:27 Stopped listening on:  localhost 15151
2023/09/19 20:29:27 [192.168.0.5:443] INFO session.go:120 Session() : Session disconnected
2023/09/19 20:29:37 Connecting to  192.168.0.5:443
2023/09/19 20:29:38 Successfully connnected 192.168.0.5:443
```

So it fails due to `Opening forwarded-tcpip channel to server failed:  ssh: rejected: administratively prohibited (open failed)`

Just in case, OpenSSH client versions that I used with `-R` option are:

```
OpenSSH_8.9p1 Ubuntu-3ubuntu0.3, OpenSSL 3.0.2 15 Mar 2022
OpenSSH_9.2p1 Debian-2, OpenSSL 3.0.10 1 Aug 2023
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
```

Doesn't seem to be an issue with opening ports on remote client since when I use ligolo-ng to forward remote ports it works as expected, also tested on different setups, looks like an RSSH bug to me

**Comment by NHAS** [comment]
Howdy.

Can you also give me the ssh command you used to get this error?

Definitely off that the server connection is dying for the client.

Could you give me server logs for this?

**Comment by itschesko** [comment]
What a speed, yeah, sure

I've tried `ssh -R 15151:127.0.0.1:15151 -J ...`, also tried on `0.0.0.0`, then in the terminal window I just accessed port 15151 with `curl http://127.0.0.1:15151`

Those are server logs since the moment of client connection till the error
```
2023/09/19 17:17:26 Loading files from /opt/reverse_ssh/bin
2023/09/19 17:17:26 Version:  v2.2.2
2023/09/19 17:17:26 Listening on 0.0.0.0:2222
2023/09/19 17:17:26 Loading private key from: /opt/reverse_ssh/bin/id_ed25519
2023/09/19 17:17:26 Server key fingerprint:  a2d4576a4bb4e44f19fe6bb4759ddb2dea8be739f736ea0e332d61a592a47217
2023/09/19 17:17:26 Loading authorized keys from: /opt/reverse_ssh/bin/authorized_keys
2023/09/19 17:17:26 Was unable to read webhooks configuration file
2023/09/19 17:17:26 Started Web Server
2023/09/19 17:17:34 [185.70.54.83:31393] INFO sshd.go:360 acceptConn() : New controllable connection with id 2d630cbd1396f24816d0d5d7be858ab5b1176099
2023/09/19 17:18:04 [[::1]:35466] INFO sshd.go:324 acceptConn() : New User SSH connection, version SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.3
2023/09/19 17:18:04 [[::1]:35466] INFO global.go:118 RegisterChannelCallbacks() : Handling channel: direct-tcpip
```

Regarding the dying server connection, I think that's probably bc I forcefully closed open RSSH terminal session bc it hangs my terminal after the `WARNING: Server requests forwarding for unknown listen_port`, but I believe it's just terminal window issue

**Comment by NHAS** [comment]
Cool I can replicate this. Not sure how its broken yet.

**Comment by itschesko** [comment]
Is it global or happens only on specific OpenSSH client versions? I've searched yesterday and found kinda similar issue with remote forwarding, for the guy there it was broken on 7.9 or smth like that but on 5.5 it worked as expected, didn't test lower client versions tho' and it was about normal ssh server, not RSSH. Maybe there are minor changes in OpenSSH forwarding logic

**Comment by NHAS** [comment]
Actually, I may have to take that replication back. Turns out I've found another weirdness when you dont define localhost as 127.0.0.1 on a machine it can cause failure to open.

**Comment by NHAS** [comment]
Ah no I can, its just a little different then I first thought

**Comment by itschesko** [comment]
I've tried `ssh -R` with `[PORT]:[localhost/127.0.0.1/0.0.0.0/other interface IP]:[PORT]`, didn't work for all cases, the last server log is for `ssh -R 15151:127.0.0.1:15151`

**Comment by NHAS** [comment]
Ah cool I've fixed it. Give me one moment and I'll do a release

**Comment by NHAS** [comment]
All done!
