### ISSUE TITLE
The client supports opening an http proxy server

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#138]
I have a suggestion, is it possible to add a function to the client to listen to an http proxy on a certain port at the current host address 0.0.0.0, so that the built-in http proxy can cooperate with the client's proxy to implement the intranet Starlink.

**Comment by NHAS** [comment]
I have no idea what this means. 

From the title Im not planning on implementing or adding an HTTP proxy server to the client as I feel that falls outside of the scope of this project. 

Thanks tho!

**Comment by tdragon6** [comment]
What I mean is that for example, there are two hosts A and B in the internal network. A can go out of the network, but B cannot go out. At this time, B cannot connect to the server through the client. If client A can deploy an http proxy server to forward traffic, In this way, client B can use the `proxy` parameter to achieve an outbound reverse connection through A's http proxy.

**Comment by NHAS** [comment]
While it doesnt open an HTTP proxy server directly. This feature already exists. 

You can use the server console command `listen` with the `-c` flag to open a server control port on a client of your choice

**Comment by tdragon6** [comment]
Thank you very much for your answer, I will research this function.
