### ISSUE TITLE
Dynamic Reverse Forwarding from Plain SSH Client

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#139]
It would be great to get the feature back to allow plain ssh clients to dynamically reverse forward a socks proxy to rssh.

So from a normal open ssh client `ssh -R 1337 myrsshserver` and then the operator can proxy through that boi

**Comment by NHAS** [comment]
Sweet, will add that back. It will be forced to bind to localhost however, just to prevent malicious clients doing weird shit.
