### ISSUE TITLE
remark 

### ISSUE THREAD

**Issue by xiaoxiaoranxxx** [NHAS/reverse_ssh#140]
Why is my Targets this way?

![Snipaste_2023-10-25_18-57-22](https://github.com/NHAS/reverse_ssh/assets/78064939/55593d42-11c5-4476-90bb-a7d556ff1d6a)
And here's what you demonstrated

![image](https://github.com/NHAS/reverse_ssh/assets/78064939/92c3e588-e47d-41ea-861f-1c00e718798c)

There will be a bit of confusion when the client is connected much, can you add a column that can note custom information

![image](https://github.com/NHAS/reverse_ssh/assets/78064939/36f64734-9997-4204-909c-5641cb033c59)

**Comment by NHAS** [comment]
I made a change to make `-t` group all the targets so it wouldnt just get endlessly long and break on small terminal sizes. 

You can still get a space delimited version of ls by doing `ls`

**Comment by NHAS** [comment]
There isnt a great way to set a comment like that, as Im trying to keep it in the format of the ssh `authorized_keys` file, you can rename your targets with the comment tho

**Comment by xiaoxiaoranxxx** [comment]
Ok, thank you for your answer

**Comment by xiaoxiaoranxxx** [comment]
Oh jeez, you're awesome, thanks for such a quick response , and for such an amazing tool


There seems to be a bug, there are more than 20 records each generated when viewing the history, this is the case for both linux and windows live


![image](https://github.com/NHAS/reverse_ssh/assets/78064939/a0a83cac-1145-4e72-a106-ee0d7230e49f)

**Comment by NHAS** [comment]
Was this comment suppose to go on the watch command feature request?


Could you potentially open this as a new issue, I'm not getting this problem when I use this on my Linux machine
