### ISSUE TITLE
Client can also bind and accept connections

### ISSUE THREAD

**Issue by lielb100** [NHAS/reverse_ssh#142]
It will be great if the at the same time the client is connecting to the server, it'll also always be listening on a port (chosen at build time or as an argument, as well as if the client should bind) to allow front connection just like a regular sshd server.

This feature will allow the chaining of multiple hosts that cannot connect to the server.
It'll work like this:
`ssh -J rssh.server <host1_id> -D 9050`
And then 
`proxychains ssh <host2_ip> -p <bind_port>`
Also, if possible, to connect directly to the client without going through the server, like if already have a different tunnel, and to be able to execute just the proxychains' command.

Nice syntax will be:
`ssh -J rssh.server,<host1_id> <host2_ip> -p <bind_port>` 

This feature will make this already amazingly done tool, the complete package.

**Comment by NHAS** [comment]
This feature already exists

**Comment by lielb100** [comment]
Can you please elaborate? I must have missed it...

**Comment by NHAS** [comment]
You can start the server port on any client with the server console terminal command "listen" with the `-c` flag

**Comment by lielb100** [comment]
How does this work? Because I can see that this requires the client to first connect to the server, and then it is able to open the bind port on the client, I'm talking about being able to state that the client should open the port even when there is no possibility to connect to the server, like at build time.

**Comment by NHAS** [comment]
Oh i see you mean you just want the client to be an sshd daemon.

Unfortunately I'm not looking to add that to the project.

There are other golang ssh projects that do that tho!

**Comment by lielb100** [comment]
Hey can you please delete this issue?

**Comment by NHAS** [comment]
Uh why? I think it's good to have a record that I don't want this project to be a bind sshd daemon.

A tad strange that you've removed the content of all your messages.
