### ISSUE TITLE
"watch" Add all online and offline history

### ISSUE THREAD

**Issue by xiaoxiaoranxxx** [NHAS/reverse_ssh#143]
"watch" Add all online and offline history

For example:

┌──(root㉿kali)-[/opt/xssh/bin]
└─#ssh 8.8.8.8 -p 3232 watch
2023/11/06 16:59:43 <- linux.xxxx.ubantu (1.1.1.1:61855 4ee6160712203e461557ab) SSH-_guess-windows_amd64 connected
2023/11/06 16:59:43 <- macbook.xxxx.macbook (1.1.1.1:61855 4ee6160712203e461557ab) SSH-_guess-windows_amd64 connected
2023/11/06 17:59:43  -> macbook.xxxx.macbook having died
2023/11/06 18:59:43  -> linux.xxxx.ubantu having died

Record the online and offline records of each shell

**Comment by xiaoxiaoranxxx** [comment]
I think you can show it this way

watch -a  --all    Displays all records
watch -l  --listen    Default watch
watch     only shows the last 10

**Comment by NHAS** [comment]
Im going to make this so that `watch` defaultly does what its always done. Just to not break peoples flows. 

I agree with `watch -a` and `watch -l <limit>`

**Comment by NHAS** [comment]
Sweet this is all added now, check it out on unstable
