### ISSUE TITLE
i wanna know where to generate the figerprint

### ISSUE THREAD

**Issue by M0r41** [NHAS/reverse_ssh#144]
I want to modify the code for one client use only one unchangeable figerprint.
I found that the figerprint often changes in server, it could be inconvenient.

**Comment by NHAS** [comment]
Sounds like you've set the server up wrong. If I had to take a stab in the dark you're not not mounting a folder to store the servers private key.

**Comment by M0r41** [comment]
thx a lot, i build it in docker, i found the problem. i use python paramiko lib to load the figerprint, it caused several connection in same ip, but only one can be used. i just want to know how to deal with it.

**Comment by NHAS** [comment]
I don't know what you mean unfortunately.

**Comment by M0r41** [comment]
i build a rssh docker and a redis to store the client figerprint. and a python web front. i use python paramiko generate private keys and load public keys from redis to access the client. but i don't know why it lead to several connections in one ip address. It may seem that client can't store the public key in memory, so when the connection interrupted and rebuild connection in a while, it may cause a new public key bind to the ip address

**Comment by NHAS** [comment]
I dunno mannnn you crazy

**Comment by M0r41** [comment]
well,thx a lot
