### ISSUE TITLE
log repetition

### ISSUE THREAD

**Issue by xiaoxiaoranxxx** [NHAS/reverse_ssh#145]
There seems to be a bug, there are more than 20 records each generated when viewing the history, this is the case for both linux and windows live

![https://user-images.githubusercontent.com/78064939/284057296-a0a83cac-1145-4e72-a106-ee0d7230e49f.png](https://user-images.githubusercontent.com/78064939/284057296-a0a83cac-1145-4e72-a106-ee0d7230e49f.png)

Linux kali 6.1.0-kali9-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux

I compiled the go environment:
go version go1.21.3 linux/amd64

**Comment by NHAS** [comment]
Can you give me the exact `watch` arguments you were using to view this? Im very confused as this shouldnt be possible

**Comment by NHAS** [comment]
Ah actually I know exactly why this is happening. Cheers!

**Comment by xiaoxiaoranxxx** [comment]
ssh 1.1.1.1 -p 80 watch -a

**Comment by NHAS** [comment]
I've pushed this directly to main and will be doing a release in a sec. Thanks for the report!
