### ISSUE TITLE
Polling Transport

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#146]
It would be great if RSSH could support polling over HTTP(S) as a transport, à la ferryman.

Very useful for when you only have HTTP/HTTPS as your egress, and websockets don't work.

**Comment by NHAS** [comment]
The first version of this now exists on unstable. 

Its still quite broken, clients that disconnect arent removed from the connection list, its a bit inefficient, etc. But its there. 

Im going to do some cleanup. 

Todo: 

- [ ] Disconnect clients correctly
- [ ] Limit connections to only public keys we know (using public keys are a password)
- [ ] Limit max number of connections per public key
- [ ] Customize comms path

**Comment by NHAS** [comment]
This is now ready enough to be on unstable for testing
