### ISSUE TITLE
HTTP_PROXY parsing should be more robust

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#147]
The HTTP_PROXY env variable can take many forms, such as `http://my-egress-lad:1234`. But, net.Dial is confused as it expects `host:port`, and this will cause an error.

When trying http_proxy, I suggest that RSSH should:
- Strip out `http://`
- If no port is specified, try both 80, and 8080

**Comment by NHAS** [comment]
This is now on unstable

**Comment by lachlan2k** [comment]
I like the changes -- perhaps they should also be applied to the `--proxy` command line flag? It would be great for that to be more versatile (and consistency).

I have to admit it took me a hot second to realise what was was breaking when I was trying to `--proxy http://foo` previously.

I'll test later to make sure it works for me.
