### ISSUE TITLE
Bash Completion Provider

### ISSUE THREAD

**Issue by ld-carapace** [NHAS/reverse_ssh#156]
### Summary

Would be awesome for RSSH to have an official ™ bash/zsh/*sh completion provider.

The idea would be if you type `ssh -J rssh` then hit tab, and it would suggest IDs/names of clients to connect to.

Perhaps the completion should look for any `ssh` command where the string `-J rssh` is present? And then users would be encouraged to have SSH config entries for rssh.

If a user has multiple RSSH servers they could name them `rssh-shell-catcher` `rssh-somethingelse`, and the completion provider would automagically query the right one.

### Motivation

It's a bit annoying that if you want to find which client to connect to, you have to typically do something like `ssh rssh ls`, to find the ID, copy it, then `ssh -J rssh <id here>`.

**Comment by NHAS** [comment]
This is now on unstable. 

To use it:

Generate your autocompletions and add it to your `bashrc`

```sh
ssh localhost -p 3232 autocomplete --shell-completion localhost:3232 >> ~/.bashrc
```

Then you can use it such as

```sh
ssh -J localhost:3232 <TAB>
# or
ssh localhost -p 3232 exec/kill/connect <TAB>
```
