### ISSUE TITLE
Sh template problem

### ISSUE THREAD

**Issue by xiaoxiaoranxxx** [NHAS/reverse_ssh#157]

**Comment by xiaoxiaoranxxx** [comment]
![image](https://github.com/NHAS/reverse_ssh/assets/78064939/8a25a830-81e6-454d-a452-3652a2090ef6)
Why don't I have the exact address of http?
The command to start is
./server --webserver  --external_address 47.92.*.* :80

**Comment by NHAS** [comment]
That is a very good question, I can replicate this behavior

**Comment by NHAS** [comment]
Long story short, because the `external_address` had no port it hit an edge case which I've now removed by using the `net.SplitHostPort` function in the golang stdlib

**Comment by xiaoxiaoranxxx** [comment]
Thank you for your reply. It turns out that my external_address did not add a port.

**Comment by NHAS** [comment]
Its also fixed in the main branch/version 2.5.1 so it'll just default to port 80 if non-was specified
