### ISSUE TITLE
Human client port restriction

### ISSUE THREAD

**Issue by Fasiru** [NHAS/reverse_ssh#166]
I don't want to expose the reversessh operator port on the Internet. So the port to which human clients connect.

There are two solutions to solve the problem:

1. The port to which human clients connect is different from the port to which RSSH clients connect. This allows me to block the port that human clients connect to on the Internet and only allow to connect from localhost.
2. The SSH server only allows connections from human clients from localhost. 

Is there already an option that allows me to do this?

**Comment by NHAS** [comment]
Hm. This not something RSSH can currently do. 

You can define allowed ip addresses for specific admin keys using the `from` directive, but I dont know if thats what you want.

**Comment by Fasiru** [comment]
Yes, that could be a solution. I will try it. 
Thank you :)

**Comment by Fasiru** [comment]
Yes, I can confirm this works. 👍

**Comment by NHAS** [comment]
Awesome! Glad it works for you!
