### ISSUE TITLE
remarks 

### ISSUE THREAD

**Issue by xiaoxiaoranxxx** [NHAS/reverse_ssh#170]
If there are dozens of shells to manage and it's easy to get confused, 
I want a feature that can define remarks

In the configuration of.ssh/config

```
[root@VM-24-10-centos ~]# cat ~/.ssh/config 
Host www
    HostName www.xxxx.com
    Port 22
    User root
    IdentityFile  ~/.ssh/id_rsa.pub
    IdentitiesOnly yes
 
Host bbs
    HostName 115.28.45.104
    User anotheruser
    PubkeyAuthentication no
```

This way I can log in directly to 

```
ssh www
ssh bbs
```

I want to always combine these to create a function, which can directly add names🫡🫡🫡

**Comment by NHAS** [comment]
This already exists. You can name clients to whatever you want in the `authorized_keys` file comment.


https://github.com/NHAS/reverse_ssh/blob/e7c52e54622168a737c5592894d85bec3758b0bd/internal/server/users/clients.go#L51

This will add the comment as a name/id that you can use.
