### ISSUE TITLE
Doubts about persistence

### ISSUE THREAD

**Issue by Gustavohenribra** [NHAS/reverse_ssh#171]
"Windows
service: Installs or removes the rssh binary as a windows service, requires administrative rights

e.g

# Install the rssh binary as a service (windows only)
ssh -J your.rssh.server.internal:3232 test-pc.user.test-pc -s service --install"

Can anyone explain to me how to use it as a service? I've tried to run it on Windows 10 but I can't, I've tried downloading the client and running the command on the client and nothing works, and after running it how can I access Windows 10 from my VPS? Would you still use docker or would it be on the machine itself?

**Comment by NHAS** [comment]
Sorry you havent provided enough information to help you with your issue. 

Saying "I've tried downloading the client and nothing works" doesnt give me a lot to go on in helping you. As the code for installing the rssh client as a windows service hasnt changed much, I'd hesitate to believe its broken with such little information. 

I can definitely confirm that the project as a whole works, and on windows for that matter. So unless I can get some replication steps from you Im going to mark this as user error. 

If you do give me some replication steps I am more than happy to have a look. 

Thanks!
