### ISSUE TITLE
unrecognized import path "inet.af/tcpproxy"

### ISSUE THREAD

**Issue by exploide** [NHAS/reverse_ssh#176]
When trying to compile latest reverse_ssh, I get the following error:

```
internal/client/handlers/tun.go:27:2: unrecognized import path "inet.af/tcpproxy": https fetch: Get "https://inet.af/tcpproxy?go-get=1": dial tcp: lookup inet.af on 127.0.0.53:53: no such host
```

I guess the import path should be changed to `github.com/inetaf/tcpproxy`. See also https://github.com/inetaf/tcpproxy/issues/39

**Comment by NHAS** [comment]
Huh I have no idea how this has worked for me. But it does seem like the.af tld was seized by the tailban out of all things. So I'll do a release to fix that.

**Comment by NHAS** [comment]
I've done an updated and pushed to main
