### ISSUE TITLE
Novice question 

### ISSUE THREAD

**Issue by TazTheworld** [NHAS/reverse_ssh#183]
Hello, 

Is it possible to set the download server to https://? 

Because windows defender blocks downloads in http://

**Comment by NHAS** [comment]
Yep! You can check the help on the server with `-h` and use the following:

`--tls`
`--tlscert`
`--tlskey`

Or if you're using docker I'd just put caddy in front of rssh, so put the rssh port on something like 4444
Then put caddy on 80/443 and reverse proxy to the rssh server in the backend
