### ISSUE TITLE
[Feature Request] Client authentication

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#2]
It is often desirable to open a reverse_ssh server up to the world, however only certain clients should be allowed to connect to it.

It would be useful to have password/token based authentication, passed with a flag (such as `./client myserver:222 --auth hunter2`) or public key auth with an adjacent key file.

Cheers :)

**Comment by NHAS** [comment]
Done. 

Effectively you can now "embed" a private key to a client, the public key of which is stored in `authorized_controllee_keys`, and validated against. 
To generate a keypair to embed you can use the make file `make client`, the resulting key is `stored in internal/client/keys`.

If there isnt any embedded key then the client will automatically generate their key, but the server will need to be run with the `-insecure` flag.
