### ISSUE TITLE
PTY Errors

### ISSUE THREAD

**Issue by monat78** [NHAS/reverse_ssh#28]
Hi... would you know how to solve it?

 ssh root@127.0.0.1 -p 44500
PTY allocation request failed on channel 0
shell request failed on channel 0

in server side:
[127.0.0.1:53800] INFO server.go:181 acceptConn() : New SSH connection, version SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
[127.0.0.1:53800] INFO global.go:98 RegisterChannelCallbacks() : Handling channel: session
[127.0.0.1:53800] INFO session.go:30 Session() : Session got request: "pty-req"
[127.0.0.1:53800] WARNING session.go:61 Session() : Unsupported request pty-req
[127.0.0.1:53800] INFO session.go:30 Session() : Session got request: "env"
[127.0.0.1:53800] WARNING session.go:61 Session() : Unsupported request env
[127.0.0.1:53800] INFO session.go:30 Session() : Session got request: "shell"
[127.0.0.1:53800] WARNING session.go:61 Session() : Unsupported request shell
[127.0.0.1:53800] INFO session.go:68 Session() : Session disconnected: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
[127.0.0.1:53800] INFO server.go:199 func1() : User disconnected: connection terminated

Regards. :D

**Comment by NHAS** [comment]
Howdy @monat78, 

The server itself doesnt support PTY requests (which is the request ssh sends to be like "hey give me a shell"). 
As the server is effectively just a jump host for your clients, try using the jump host syntax. 

E.g 

```bash
ssh -J your.rssh.server <client_id>
```

Where the client id can be found by doing:
```
ssh your.rssh.server ls
```

**Comment by NHAS** [comment]
At one point I was doing everything via PTY, but there are some complexities with that, which make it more annoying to manage. 
If a lot of people continually have this same issue, I may add it back in :)

**Comment by monat78** [comment]
Primero de todo grácias por contestar. Tengo  o puedo arreglarlo de alguna manera??...  es que es muy interesante la verdad este sistema.. almenos queria probarlo bien jeje... muchas grácias por contestar... me pasa en un amd64 y raspbian. Me interesaba para administrar varias raspberrypi.

**Comment by monat78** [comment]
First of all thanks for answering. Do I have or can I fix it in some way? ... is that the truth is that this system is very interesting .. at least I wanted to test it well hehe ... thank you very much for answering ... it happens to me on an amd64 and raspbian. I was interested in managing several raspberrypi.

**Comment by monat78** [comment]
I run the server,, i have one client...

ssh localhost -p 4400 ls
  output is empty line

ssh localhost -p 4400 ls -t
         Targets
+----+----------+------------+
| ID | Hostname | IP Address |
+----+----------+------------+
INFO server.go:181 acceptConn() : New SSH connection, version SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
INFO global.go:98 RegisterChannelCallbacks() : Handling channel: session
INFO session.go:30 Session() : Session got request: "env"
WARNING session.go:61 Session() : Unsupported request env
INFO session.go:30 Session() : Session got request: "exec"
INFO session.go:55 Session() : Session disconnected: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
INFO server.go:199 func1() : User disconnected: connection terminated

I try to give you as much information as I can ...

**Comment by NHAS** [comment]
So, it isnt a bug per say. It just happens to be you're using the server wrong when you connect to it. 

So instead of trying to connect to the server directly. You need to show your clients. 

DO this: 

```
ssh your.rssh.server ls
```

And it should list your currently connected clients. 

Then to connect to one of them, you do `ssh -J your.rssh.server <client_id>`. Does that make sense?

**Comment by monat78** [comment]
i can't view client_id or table

**Comment by NHAS** [comment]
Okay, I think you havent connected your client/s to the RSSH server.

**Comment by monat78** [comment]
![one](https://user-images.githubusercontent.com/16297560/147842790-c6c452be-7e77-45f6-ad9f-fba52129ebd4.png)
![two](https://user-images.githubusercontent.com/16297560/147842791-ddaa9361-0598-4fd7-b12d-ab623648edc0.png)

**Comment by NHAS** [comment]
Oh dang. I see what you mean!

**Comment by monat78** [comment]
jeje :D if I can help you with something else ...

**Comment by NHAS** [comment]
Hm, I cant replicate this on my system. Im doing an amd64 -> amd64 system though (although that really shouldnt be breaking it)

**Comment by NHAS** [comment]
Could you show me the output of the client? 

```
./client --foreground your.rssh.server
```

**Comment by monat78** [comment]
![client](https://user-images.githubusercontent.com/16297560/147842852-a7e4beda-a6c6-4db5-8f88-9a2d89f6fe66.png)

**Comment by NHAS** [comment]
Im assuming that this still shows the same on the server side?

**Comment by monat78** [comment]
server side: 

INFO server.go:181 acceptConn() : New SSH connection, version SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
INFO global.go:98 RegisterChannelCallbacks() : Handling channel: session
INFO session.go:30 Session() : Session got request: "env"
WARNING session.go:61 Session() : Unsupported request env
INFO session.go:30 Session() : Session got request: "exec"
INFO session.go:55 Session() : Session disconnected: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
INFO server.go:199 func1() : User disconnected: connection terminated

**Comment by monat78** [comment]
I have downloaded the current one and the release .. they do the same to me.

**Comment by monat78** [comment]
debug3: Ignored env PATH
debug3: Ignored env MAIL
debug3: Ignored env SSH_TTY
debug3: Ignored env _
debug3: Ignored env OLDPWD
debug1: Sending command: ls -t
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 2097152 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: chan_shutdown_read (i0 o1 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> closed
debug3: channel 0: will not send data after close
        Targets
+----+----------+------------+
| ID | Hostname | IP Address |
+----+----------+------------+
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 e[write]/0 fd -1/-1/6 sock -1 cc -1)

debug3: send packet: type 1
debug3: fd 1 is not O_NONBLOCK
Transferred: sent 2052, received 1132 bytes, in 0.0 seconds
Bytes per second: sent 365003.7, received 201356.8
debug1: Exit status -1

**Comment by NHAS** [comment]
The release is quite old now in terms of changes (been meaning to update it). 

At the moment just use current master branch. 

Try compiling & running a client on your amd64 host, and connecting it to your server?

**Comment by monat78** [comment]
I have also tried the client, server, and then cnc but it does the same.

I use the current master.

**Comment by monat78** [comment]
It seems that the client connects, but I can't see the information table, but when trying to see the list it gives me the empty list.

**Comment by NHAS** [comment]
Yep, essentially it may be because the adding of the client to the list is blocking for some reason. Let me get back to you.

**Comment by monat78** [comment]
no problem :D

**Comment by NHAS** [comment]
Right, I've pushed a little thing that will give us better insight into if we ever actually end the client addition. Want to try it out?

**Comment by monat78** [comment]
ok

**Comment by monat78** [comment]
![1](https://user-images.githubusercontent.com/16297560/147843072-59f96b82-b286-4c6c-a8ae-e8759d294b33.png)

**Comment by monat78** [comment]
ssh localhost -vvv -p 4400 ls -t

![image](https://user-images.githubusercontent.com/16297560/147843087-c78bd058-651e-42e0-a347-561052af6432.png)

**Comment by monat78** [comment]
debug3: Ignored env SSH_CLIENT
debug3: Ignored env PATH
debug3: Ignored env MAIL
debug3: Ignored env SSH_TTY
debug3: Ignored env _
debug1: Sending command: ls -t
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 2097152 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: chan_shutdown_read (i0 o1 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> closed
debug3: channel 0: will not send data after close
        Targets
+----+----------+------------+
| ID | Hostname | IP Address |
+----+----------+------------+
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 e[write]/0 fd -1/-1/6 sock -1 cc -1)

debug3: send packet: type 1
debug3: fd 1 is not O_NONBLOCK
Transferred: sent 2052, received 1132 bytes, in 0.0 seconds
Bytes per second: sent 442182.1, received 243932.8
debug1: Exit status -1

**Comment by NHAS** [comment]
Ohhhhhhhhhhhh I see the problem. Okay, somehow your client has its public key in authorized_keys, rather than authorized_controllee_keys, which means the server is treating it as a real user. 

I.e its thinking the client is a user who wants to control stuff

**Comment by NHAS** [comment]
Did you use the make file to build and generate keys?

**Comment by monat78** [comment]
yes... i try it with add in authorized_controllee_keys

**Comment by NHAS** [comment]
And remove the key from authorized_keys :)

**Comment by monat78** [comment]
i try it :D

**Comment by monat78** [comment]
I'm going to start over ... I'll tell you

**Comment by monat78** [comment]
all very well, and sorry
![2](https://user-images.githubusercontent.com/16297560/147843420-17c0a1c9-9b3b-470f-a3c1-ea2c621ce2b8.png)

**Comment by monat78** [comment]
a delight: D

ssh -J localhost:4400 1100bcde8d6da7ab294cf296a48237ac4d071187  

all ok  :D

**Comment by NHAS** [comment]
Success! Fantastic, glad you got it working. 

Ironically in solving this I actually did find a small bug in the shell selection code. So thanks! Enjoy Im going to close this issue now.
