### ISSUE TITLE
Can't change directory on Windows

### ISSUE THREAD

**Issue by mrshellx** [NHAS/reverse_ssh#30]
Hi, 
When I try to change directory in windows client I can't change directory. Any suggestions?

**Comment by NHAS** [comment]
Hi there, I just need a few more details. 

Specifically, what version of windows are you running this on? 
Is this when you try and use 'cd' in the actual shell itself?

**Comment by mrshellx** [comment]
Hİ again,
I don't know what happened, but I was able to change directory like this: 'ssh -J <server>:3232 <client_id> -t' 

Thanks for your time <3

**Comment by NHAS** [comment]
Im glad you got it working and thanks for the solution. I'll keep it in mind if someone else has the same issue, 

If it happens a lot it may be a bug haha

**Comment by mrshellx** [comment]
For info : Windows 10 Pro Version 21H2 Build 19044.1466
