### ISSUE TITLE
Thanks for the project + question

### ISSUE THREAD

**Issue by presianbg** [NHAS/reverse_ssh#33]
Hi,

Thanks for the awesome project, really neat.
I picked it up from this Talos [blogpost](https://blog.talosintelligence.com/2022/03/from-blackmatter-to-blackcat-analyzing.html) , but when searched for it, the result was two repos with identical name and almost same functionalities baked in:

- obviously this repo
- and this one [reverse-ssh](https://github.com/Fahrj/reverse-ssh)

So... I suppose it's a coincidence, but still the projects are very similar and I got confused.

Cheers,
PY

**Comment by NHAS** [comment]
Ah interesting, always interesting to see *almost* your project be used for malware. Thanks for sharing this! 

It would be nice to differentiate the two projects, just happens to be luck of the draw. I started this a few months before the other project haha.
