### ISSUE TITLE
Failed to load private key (id_ed25519): open id_ed25519: no such file or directory

### ISSUE THREAD

**Issue by presianbg** [NHAS/reverse_ssh#40]
Hi,

I'm trying to run the latest version, but the server is failing to start with:
```
└─$ ./server 0.0.0.0:3232
2022/04/18 21:11:22 Listening on 0.0.0.0:3232
2022/04/18 21:11:22 Failed to load private key (id_ed25519): open id_ed25519: no such file or director
```

Not sure what the problem is, but seems like commit 7d8fee332babef6f1d772d887e15a371120f13f8 broke it. 
Copying the `private_key` from `internal/client/keys/private_key` to `bin/id_ed25519` seems to be a workaround. 

Cheers,
PY

**Comment by NHAS** [comment]
Cheers, seems I broke it when I changed from using flags to my own parser. 

Thanks! 

Should be all fixed now.
