### ISSUE TITLE
32bit windows client

### ISSUE THREAD

**Issue by presianbg** [NHAS/reverse_ssh#42]
Hi,

When I try to generate a 32 bit client via the `catcher$`, it fails with:

```
catcher$ link --name payload32 --goos windows --goarch 386        
Error: exit status 2
# github.com/NHAS/reverse_ssh/pkg/winpty
../pkg/winpty/embed_386.go:13:14: undefined: embed
../pkg/winpty/embed_386.go:17:9: undefined: windows
../pkg/winpty/embed_386.go:43:15: undefined: os
../pkg/winpty/embed_386.go:43:39: undefined: errors
../pkg/winpty/embed_386.go:43:54: undefined: os
../pkg/winpty/embed_386.go:44:33: undefined: path
../pkg/winpty/embed_386.go:48:9: undefined: ioutil
../pkg/winpty/embed_386.go:54:15: undefined: os
../pkg/winpty/embed_386.go:54:41: undefined: errors
../pkg/winpty/embed_386.go:54:56: undefined: os
../pkg/winpty/embed_386.go:54:56: too many errors
```

Not sure how to continue with the troubleshooting. 
Cheers,
PY

**Comment by NHAS** [comment]
Ah thats annoying! 
I dont have time right now, but I'll get that looked at (and hopefully fixed) in the next couple days.

**Comment by NHAS** [comment]
Well, I cant comment for whether the 386 version of this works. But it will now compile, thanks for pointing that out!

**Comment by presianbg** [comment]
> Well, I cant comment for whether the 386 version of this works. But it will now compile, thanks for pointing that out!

Works flawlessly ! Thanks!

**Comment by NHAS** [comment]
Awesome! Thanks for telling me, I dont have a 386 windows vm lying about.
