### ISSUE TITLE
Client stops working

### ISSUE THREAD

**Issue by amdyes-droid** [NHAS/reverse_ssh#43]
Code version: latest
Test environment: kali 2022.01

When I repeatedly connect the client on the server side in a short period of time, the client and server will be disconnected, and the client cannot continue to work and reconnect.
This kind of problem also occurs in mobaxterm. After connecting to the jump client for many times, the client cannot work. What is the reason?

![1](https://user-images.githubusercontent.com/75684981/167260666-bfe111ab-072f-4ef2-b6ec-cd0a499bd52b.png)
![2](https://user-images.githubusercontent.com/75684981/167260670-7f2bc2cb-fe85-47fb-b47e-1cfac7b8fa48.png)
![3](https://user-images.githubusercontent.com/75684981/167260673-90acf179-5ffb-4300-8ab8-0b855bae3f38.png)
![4](https://user-images.githubusercontent.com/75684981/167260676-eb7ccbeb-c6de-49f3-9fb9-d74a66e609da.png)

**Comment by NHAS** [comment]
Damn! What an interesting bug, I'll see if I can replicate and get back to you

**Comment by NHAS** [comment]
Sweet! Seems I can replicate it.

**Comment by NHAS** [comment]
I believe my most recent commit has fixed this. However, Im not entirely certain why doing what I've done (which is closing a file descriptor I open at the start of the program) has fixed it. 

Please test it out, and see if this has fixed it for you.

**Comment by amdyes-droid** [comment]
yes, this seems to be solved, didn't expect this to be the problem :)

**Comment by NHAS** [comment]
You and me both. What a weird bug.
