### ISSUE TITLE
Can't connect via hostname if it includes a dash

### ISSUE THREAD

**Issue by neben** [NHAS/reverse_ssh#44]
Connecting via hostname does not work if the hostname includes a dash.

```
catcher$ connect root.foobar-1f1234
root.foobar-1f1234 Not found.
```

Connecting via ID or IP works fine.

Apparently this only applies to `connect` and connection via JumpHost. Using `exec`, however, works as expected, i.e., it resolves the hostname just fine.

**Comment by NHAS** [comment]
Huh, how odd, I thought I'd fixed this bug a long while ago. 

When you run `hostname` on the target, what is the reported hostname? I should have a regex that replaces all special characters with dashs (as ssh only allows domains in jumphost syntax, so windows machines with slashes and @'s become sad)

**Comment by NHAS** [comment]
Ah it seems I was a tad over zealous when I fixed this last. I essentially replace all special characters with `.`.

So your host will be able to be connected to, if you do `connect root.foobar.1f1234`, this is a bug in the display and I shouldnt be replacing dashes as their valid in a domain. 

Handy hint, you can type `connect root<TAB>` and it will auto complete the correct entry.

**Comment by NHAS** [comment]
Should be fixed now. I'll wait for you to give it a test, if all is gravy I'll close this.

**Comment by neben** [comment]
Thanks @NHAS for the quick fix (and the hint), works great now!
