### ISSUE TITLE
Tuntap integration 

### ISSUE THREAD

**Issue by joe-butler2** [NHAS/reverse_ssh#46]
Not sure how complicated it would be to add but it could be useful to add tuntap support (`ssh -w`) similar to [ligolo](https://github.com/nicocha30/ligolo-ng) as an alternative to using a socks proxy, different tool or manually configuring a tunnel back to the bastion.

Edit: I'm not sure how you give issues a label, github wouldn't let me assign one

**Comment by NHAS** [comment]
Hi Joe, 

Thanks for this feature! I definitely think its worth having a look at. However there are some caveats, I'm going to try and avoid requiring the client binary to have administrative/root privileges, which will most likely mean I wont be setting up a full tun/tap interface on the client side. 

This has the knock on effect that things like raw ICMP will not work. 

Having a look at ligolo, I can see they effectively act as a proxy much the same to how the dynamic and local forwards (`-D` and `-L`) work in ssh already. They dont let you proxy arbitrary network traffic as their client is also unprivileged.

**Comment by joe-butler2** [comment]
> Hi Joe, 
> 
> Thanks for this feature request! I definitely think its worth having a look at. However there are some caveats, I'm going to try and avoid requiring the client binary to have administrative/root privileges, which will most likely mean I wont be setting up a full tun/tap interface on the client side. 
> 
> This has the knock on effect that things like raw ICMP will not work. 
> 
> Having a look at ligolo, I can see they effectively act as a proxy much the same to how the dynamic and local forwards (`-D` and `-L`) work in ssh already. They dont let you proxy arbitrary network traffic as their client is also unprivileged.  

Yeah, I think it's key to retain the current requirements of the project rather than requiring the client to be ran in a privileged context.

**Comment by NHAS** [comment]
In reference to our emails you mentioned that the default forwarding + nmap was quiet slow. To speed this up, I could set a timeout on the client side for the TCP connection its trying to create. 

Currently it will wait forever, which means on hosts that have a default DROP policy (rather than reject) it will hang until nmap gives up.

**Comment by joe-butler2** [comment]
> In reference to our emails you mentioned that the default forwarding + nmap was quiet slow. To speed this up, I could set a timeout on the client side for the TCP connection its trying to create. 
> 
> Currently it will wait forever, which means on hosts that have a default DROP policy (rather than reject) it will hang until nmap gives up. 

That sounds like a good solution yes!

**Comment by NHAS** [comment]
Sweet, I'll set the timeout to the same as ligolo (5 seconds)

**Comment by NHAS** [comment]
On the unstable branch it now has a 5 second timeout for local forward dialing, e.g when its trying to start the connection it will have a 5 second timeout but not have a timeout during the actual connection.

**Comment by TechSupportJosh** [comment]
+1 for this
Having an integrated sshuttle/ligolo would make this an incredibly powerful tool for pivoting around networks

**Comment by NHAS** [comment]
Well, to delve into my reading and thinking today. 

The tun extension is defined here: https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL?annotate=HEAD section 2.3

SSH supports both layer 3 and layer 2 tun/tap devices with the `-w any:any` and `-w any:any -o Tunnel=ethernet` options respectively. 

In general tuntap presents a problem for the RSSH client. To do proper tuntap you need administrative privileges and tuntap isnt native to windows. 
Other projects, such as `sshuttle` and `ligolo` have solved this by writing compatibility layers between input packets and the output network. This has its limitations, namely restricted to L3 and lacking true ICMP support (tcp/udp only).

So to roughly sum it up:

- True tuntap 
   - \+ Fast
   - \+ Able to support L3 and L2
   - \+ Easier to implement
   - \- Adds an additional interface (i.e very noisy)
   - \- Requires administrative privs 
   - \- No windows unless I write a method with a specific tuntap driver which... is out of the question
-  Compat tuntap
   - \+ Works on windows
   - \+ Doesnt add an additional interface
   - \- Most probably has a reduced throughput 
   - \- L3 Only
   - \- \- Current local or remote forwards are basically the same as this

There is also a question of client bloat, as I would like to try and keep the client somewhat small. 

So those points aside, the question comes back to you lot. 

Are you looking to have a true site to site vpn using rssh (i.e using true tuntap)?
What does the current feature set lack?

**Comment by joe-butler2** [comment]
> Well, to delve into my reading and thinking today. 
> 
> The tun extension is defined here: https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL?annotate=HEAD section 2.3
> 
> SSH supports both layer 3 and layer 2 tun/tap devices with the `-w any:any` and `-w any:any -o Tunnel=ethernet` options respectively. 
> 
> In general tuntap presents a problem for the RSSH client. To do proper tuntap you need administrative privileges and tuntap isnt native to windows. 
> Other projects, such as `sshuttle` and `ligolo` have solved this by writing compatibility layers between input packets and the output network. This has its limitations, namely restricted to L3 and lacking true ICMP support (tcp/udp only).
> 
> So to roughly sum it up:
> 
> - True tuntap 
>    - \+ Fast
>    - \+ Able to support L3 and L2
>    - \+ Easier to implement
>    - \- Adds an additional interface (i.e very noisy)
>    - \- Requires administrative privs 
>    - \- No windows unless I write a method with a specific tuntap driver which... is out of the question
> -  Compat tuntap
>    - \+ Works on windows
>    - \+ Doesnt add an additional interface
>    - \- Most probably has a reduced throughput 
>    - \- L3 Only
>    - \- \- Current local or remote forwards are basically the same as this
> 
> There is also a question of client bloat, as I would like to try and keep the client somewhat small. 
> 
> So those points aside, the question comes back to you lot. 
> 
> Are you looking to have a true site to site vpn using rssh (i.e using true tuntap)?
> What does the current feature set lack that this feature adds? 
> 
I think in terms of keeping the project as you initially intended, true tuntap might stray a little too far and be too much work compared to the compat alternative which would suffice for the use case I have currently

**Comment by NHAS** [comment]
Getting close to having this working, unfortunately getting some very odd errors from ssh.

```
debug2: channel 0: rcvd adjust 132
debug2: channel 0: rcvd adjust 84
channel_input_data: channel 0: get data: incomplete message
```
And UDP appears to lock up at this stage.

**Comment by NHAS** [comment]
I've now implemented this on the unstable branch, please test it out @TechSupportJosh or @joe-butler2, seems to work for me :)

**Comment by joe-butler2** [comment]
> I've now implemented this on the unstable branch, please test it out @TechSupportJosh or @joe-butler2, seems to work for me :)

From what I can tell, it seems to be working perfectly, nice job!

**Comment by NHAS** [comment]
Sweet, after I get confirmation from Josh, I'll probably do a release!

**Comment by TechSupportJosh** [comment]
Looks great, thank you! :)
