### ISSUE TITLE
Links are not re-generated when external address changes

### ISSUE THREAD

**Issue by TechSupportJosh** [NHAS/reverse_ssh#48]
As the title says, when links are created, they embed the current external address into the binary. However, if you restart the server and change the external address (common on OSCP, CTFs, etc. where you may have a different IP/port for each service), they keep the previous embedded address, rather than it being rebuilt with the new address.

If this is intended, it'd be nice for the links to display what address they have embedded within them inside the server menu.

**Comment by NHAS** [comment]
Yep! This isnt intended (although it isnt designed to change as I didnt think of it)

I'll fix this

**Comment by NHAS** [comment]
With further consideration, Im not going to regenerate the binaries on startup, as people may want to generate binaries for different external hosts on purpose, and it becomes a bit jank to cope with that. 

So I've made the cache and `link -l` command print the binaries homeserver/callback.
