### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by neben** [NHAS/reverse_ssh#53]
I really like that you've added webhook support. There are two things that make it unnecessarily difficult to use, however:

1. The suffix `rssh_webhook` [is added to the webhook](https://github.com/NHAS/reverse_ssh/blob/4ecca500d2bb41e619dd1cea2b8262fdbfa65768/internal/server/webhooks/server.go#L111). This is a problem, as, e.g., Slack and Mattermost generate webhooks to use, and they don't expect that the generated webhook is appended with a suffix (and therefore break). Can this be removed?
2. Slack (and Mattermost, which is similar) expect the [main text message to be transmitted in the `text` key/value of the payload](https://api.slack.com/messaging/webhooks#posting_with_webhooks). It would be great if this key could be added to contain a summary of the event. This would allow users to directly display events in Slack/Mattermost without requiring further ingress processing. It could also be a switch that can be set while adding a webhook.

**Comment by NHAS** [comment]
Hello! 
These are great suggestions, I personally dont use slack or mattermost myself and just use it to feed a small program that I myself wrote.

**Comment by NHAS** [comment]
Sweet as, I have a new implementation on the unstable branch, please play around with it, if it suits your needs then I'll merge it to master

**Comment by neben** [comment]
Really nice! Works out of the box :)

![image](https://user-images.githubusercontent.com/1236695/182603937-44a3711a-3321-4b68-884d-c2e18024abb8.png)

**Comment by neben** [comment]
I'd have one last request for this feature: Could you make the webhook configurable via the startup parameter of the server binary? That would allow me to persistently activate the webhook on startup. Maybe something like this:

```
./server --webhook https://my.server/my.hook 0.0.0.0:3232
```

Also, might be nice if more than one webhook could be set, as is currently possible via the CLI.

**Comment by NHAS** [comment]
Great! Glad to see that it just works (tm) 

I think being able to specify webhooks via the command line is reasonable, so I'll add that

**Comment by NHAS** [comment]
Ah! Actually this feature already exists, and is just very poorly documented. 

When you activate a webhook, the server will write `config.json` to its working directory, so that the webhooks will persist across reboot/program restart. 

`config.json` format:

Map of strings to bool. The bool indicates whether the rssh server should check if the TLS certificate is valid or not. 

Example:
```
{"http://localhost:8111/noot/noot":true}
```

**Comment by NHAS** [comment]
Hope this helps! Im going to close this comment as the feature already vaguely exists. If you feel Im missed some nuance of what you were asking feel free to reopen it.
