### ISSUE TITLE
Optionally compress the client binary served via link

### ISSUE THREAD

**Issue by neben** [NHAS/reverse_ssh#54]
I use the client to remote control some IoT gateways. They have very limited storage capacity for the overlay file system, so every MB counts. Now I have to manually compress the client binaries with `upx`, which is why I can't use the builtin `link` feature of the server. It would be great if the `link` command could optionally compress the generated client binary with `upx`. As for the location of the `upx` binary, it could be expected to be in the same directory as the server binary, i.e., `./upx`.

I saw that you once had `upx` activated for the `release` target, but then [removed it due to concerns with AV](https://github.com/NHAS/reverse_ssh/commit/d5ddcc47aa37bbed4721ac30ea70b9b983cff97b). Can you elaborate a bit on this? Thanks!

**Comment by NHAS** [comment]
I think having this as an optional feature in `link` is quite a good idea. 

I've just gone to confirm my thoughts that the UPX loader is detected as malicious with a tiny hello world example and have found that it isnt detected, (although go in general is detected as a virus on windows? apparently?).

I'll hedge my bets and say that it often is mistakenly detected: https://github.com/upx/upx/issues/337

However I still think adding the `--upx` option to the link command would be good

**Comment by NHAS** [comment]
This is now on the unstable branch, try it out with `link`, if it works feel free to close the issue :)
