### ISSUE TITLE
Compatibility issue under windows

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#58]
https://github.com/NHAS/reverse_ssh/blob/eb03410c687402125b33bfffbaf17878c1c9fdfe/internal/client/handlers/shell_windows.go#L69

This absolute path will cause failure when the system is not installed in the windows directory under the C drive

**Comment by NHAS** [comment]
Has this caused you issues?

**Comment by lachlan2k** [comment]
Who even does that lmao?

**Comment by shanjunmei** [comment]
> Has this caused you issues?

Unfortunately, there are multiple systems in my computer. The newly installed test system is just not in the c drive - -

**Comment by shanjunmei** [comment]
> Who even does that lmao?

In the case of multiple systems, this is not too uncommon- -

**Comment by NHAS** [comment]
Its quite uncommon in my experience. But regardless the program now uses `LookPath` to try and determine where the binary is. Please test this on your weird systems, as I literally cant make my vm do this

**Comment by shanjunmei** [comment]
> Its quite uncommon in my experience. But regardless the program now uses `LookPath` to try and determine where the binary is. Please test this on your weird systems, as I literally cant make my vm do this

thanks ，it's work fine now
