### ISSUE TITLE
./server log says ./client connnected but ssh command from Human Client has no output

### ISSUE THREAD

**Issue by catInOrbit** [NHAS/reverse_ssh#59]
Hi, I'm quite new to this reverse_ssh tool so I'm not sure if my setup is right, I'm having some issue where I can't connect to any currently connected RSSH clients

### Setup
I already tested normal ssh connection from all clients to servers and server's `authorized_keys` already contains public keys from client 

**- Server:**
```
$ ./server --insecure 0.0.0.0:3235
2022/08/10 02:50:21 Version:  v1.0.5-2-geec2410
2022/08/10 02:50:21 Listening on 0.0.0.0:3235
2022/08/10 02:50:21 Loading private key from: id_ed25519 (/home/ubuntu/reverse_ssh/bin/id_ed25519)
2022/08/10 02:50:21 Server key fingerprint:  96c8a4a14f15d6e4d0472b9c3010ce870b4523d1c648623ec7b4aefa236d4e3f
2022/08/10 02:50:21 Loading authorized keys from: authorized_keys
```

port 3235 is open 
```
$ netstat -na | grep :3235
tcp6       0      0 :::3235                 :::*                    LISTEN   
```

**- RSSH Client**
 (server IP masked with ****)
```
$ ./client --foreground ****:3235
2022/08/10 09:50:36 Connecting to  ****:3235
2022/08/10 09:50:37 [client] WARNING client.go:117 func1() : No server key specified, allowing connection to ****:3235
2022/08/10 09:50:38 Successfully connnected ****:3235
```

After issuing ./client , server side log says:
```
$ ./server --insecure 0.0.0.0:3235
2022/08/10 02:50:21 Version:  v1.0.5-2-geec2410
2022/08/10 02:50:21 Listening on 0.0.0.0:3235
2022/08/10 02:50:21 Loading private key from: id_ed25519 (/home/ubuntu/reverse_ssh/bin/id_ed25519)
2022/08/10 02:50:21 Server key fingerprint:  96c8a4a14f15d6e4d0472b9c3010ce870b4523d1c648623ec7b4aefa236d4e3f
2022/08/10 02:50:21 Loading authorized keys from: authorized_keys
2022/08/10 02:50:38 INFO sshd.go:331 acceptConn() : New controllable connection with id 6763e31fe6477084c2910ff515515d55cbc8df29
```

### Problem
All is fine and good so far , however when it comes to Human Client side listing out connected targets in server, nothing is output
`
$ ssh **** -p 3235 help`
--> Just blank, no output

`$ ssh **** -p 3235 ls -t`
--> Just blank, no output

Logs from Server side:
`2022/08/10 03:09:33  INFO sshd.go:331 acceptConn() : New controllable connection with id ebad83c1e19638b9ecbf1cc9acef871c7aba5a55`

Normal ssh works fine

At this point I'm not sure if reverse_ssh is running correctly or if I have to do any additional setup in term of SSH config so would be great if anyone can help me out with this

**Comment by NHAS** [comment]
Hi there, this is extremely odd. 

From what you've said here, this should be working. Can you give me some details on what version of rssh you're using

**Comment by NHAS** [comment]
Scratch that, I can see what version you're using. I'll try replicate

**Comment by NHAS** [comment]
There are two files that keys should be in:

`authorized_controllee_keys`: This file contains client binary keys and should *not* have your public key in it
`authorized_keys`: This should only have human keys in it

I suspect you've put your public key in the `authorized_controllee_keys` file.
