### ISSUE TITLE
Obfuscate the client

### ISSUE THREAD

**Issue by presianbg** [NHAS/reverse_ssh#68]
Hi,

I love your project, thank you for supporting and developing it.
Something cool that may improve the opsec during engagement is having the client obfuscation.

I've just came across this project -https://github.com/burrowers/garble
Also this post showing practical usage of it:
https://posts.specterops.io/get-your-socks-on-with-gtunnel-4a70a9b82b24

What do you think ?

Cheers,
PY

**Comment by NHAS** [comment]
Howdy! 

I've been thinking about adding garble to the server `link` command for ages and just never got around to it.

With you expression your want for it, I'll add it in the next couple days :)

**Comment by presianbg** [comment]
Awesome !!! 
Just make it sure you use the latest source code, not the release... because of this issue:
https://github.com/burrowers/garble/issues/577

Just tested and it compiles the binaries and seems to work just fine. 
Haven't tested the `-tiny`, `-literals` and `-seed=random` , but you should know better than me if those are needed.

**Comment by NHAS** [comment]
Howdy @presianbg this now lives on the unstable branch. Fee free to test it out with `link --garble`. 

Feel free to close the issue once you have
