### ISSUE TITLE
feat req: Allow user to specify shell on connect

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#69]
Allow a user to specify the shell when they connect. E.g. `connect --shell=/bin/zsh foo.bar` and `connect --shell=/bin/bash foo.bar`.

Eventually, this could re-open the door to allow the embedding of things like Busybox. So, a user might be allowed to embed `my-favorite-sh` into the client binary, and run `connect --shell=my-favourite-sh foo.bar`. The RSSH client would then execute this in-memory.

**Comment by NHAS** [comment]
Will do chief

**Comment by NHAS** [comment]
This is now on the unstable branch. Go ham

**Comment by lachlan2k** [comment]
poggies
