### ISSUE TITLE
Ability to run as a windows service

### ISSUE THREAD

**Issue by ChrisPritchard** [NHAS/reverse_ssh#70]
In a few 'engagements' I have needed to replace a windows service binary to hijack the account running the service. reverse_ssh golang clients compiled for windows do not respond to the start/status requests made by the windows service system, so do not start properly and are quickly killed. 

To get around this, I have built basic .NET windows service projects that simply call the reverse_ssh binary on start, but this is a bit annoying. 

The x/sys golang library suports creating windows services - this issue proposes that this functionality be built into the windows client build so that the windows client can serve both as a standalone executable and a windows service as needed - there is a .IsWindowsService method in this library that should be able to change the operating mode based on context

**Comment by ChrisPritchard** [comment]
Existing state of this shambles of a project:
![no-service-for-you](https://user-images.githubusercontent.com/30073148/197055718-41424813-a15f-4d57-bc3e-6b171c9374a0.png)

**Comment by NHAS** [comment]
The project already uses what you describe to determine if its in a windows service. 

![image](https://user-images.githubusercontent.com/6820641/197056622-f9da3fa7-17fa-427e-8727-3fb92a166de6.png)

![image](https://user-images.githubusercontent.com/6820641/197056666-52f0bf09-a3c3-4aa0-b8fa-f4bdc8714039.png)

**Comment by NHAS** [comment]
Whats missing seems to be the start command

**Comment by ChrisPritchard** [comment]
Oh. Alright ill tweak that and test it

**Comment by ChrisPritchard** [comment]
The issue is described in the original comment, where you are hijacking an existing service to assume its identity. That is, for example, you have write access over a binary or a binary's location used by a service that isn't presently running or you can stop and start. You replace the binary then start the service - at present this will fail with the message in the prior screenshot.

**Comment by NHAS** [comment]
Hm, thanks. 

I think it may be due to this: https://github.com/golang/go/issues/44921

As I cant spot anything that would make rssh unable to communicate as a service otherwise

**Comment by ChrisPritchard** [comment]
Hmm okay. Ill do some testing - see if it functions properly with a low privilege service

**Comment by NHAS** [comment]
Please try with the unstable branch, I've just bumped the modules

**Comment by ChrisPritchard** [comment]
Just tried and it starts fine now, ta. Working well with nt authority\system coming through for a service run as LocalSystem. However, it won't stop properly:
![no-service-stop](https://user-images.githubusercontent.com/30073148/197062453-d28d8774-9363-48fb-b0a2-fa9144b963eb.png)
Somewhat debatable if this is an issue - a service that won't stop is possibly suspicious, but stopping a rssh client is not really what you want anyway

**Comment by ChrisPritchard** [comment]
It can still be stopped by killing the client from the rssh catcher interface. I'm fine to close this issue, ta.

**Comment by NHAS** [comment]
Ah yes, actually thats a bug funny enough. The break statement is breaking the switch rather than the outer for loop

**Comment by NHAS** [comment]
This change is now on unstable
