### ISSUE TITLE
Helper shell script doesn't work with Busybox-based distros

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#72]
Currently, the lonk `.sh` helper relies on the `#!/bin/bash` shebang. This breaks in distros like Alpine which don't have bash, and instead have ash. In these distros, the script falls back to plain `sh` and do a sad, due to bash-specific syntax.

Suggestions:
* Alter the script to be compatible with plain `sh`
* Maybe even detect the busybox wget user-agent and change to `#!/bin/ash` as a lazy quick fix?

**Comment by NHAS** [comment]
Thanks for this, I'll look into resolving this bug as soon as I can.

**Comment by NHAS** [comment]
Solution to this will be making the script compatible with `sh` I think.

**Comment by NHAS** [comment]
This is now on unstable

**Comment by exploide** [comment]
Since you are working on making the script more compatible, consider replacing the `which curl` and `which wget` calls with `command -v curl >/dev/null 2>&1`. This is the POSIX compliant solution. `which` might not behave as expected. See https://stackoverflow.com/a/677212

**Comment by NHAS** [comment]
Ah grand, thanks, I'll do that

**Comment by NHAS** [comment]
Done
