### ISSUE TITLE
Webhook not work because content is not in good body key

### ISSUE THREAD

**Issue by Suniron** [NHAS/reverse_ssh#73]
Hey,

I tried to add a Discord webhook but i received nothing.

I think the reason is because the content is not sent in a good key.
This is not the same property between multiple webhook system.

For example, the content to send by a **Discord webhook** must be included in a `content` key but for a **Teams webhook**, it must be in a `text` key.

Could you add a way to choose the custom key to put content in ?

We can use it like `webhook --on https//discord.com/api/webhooks/mywebhookprovider --custom-key content`
 
Thank's a lot by advance ! :)

**Comment by NHAS** [comment]
Hi there! Thanks for your issue, I believe if you use the discord `/slack` compatibility endpoint, this works perfectly fine. 

See the information here: https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

**Comment by Suniron** [comment]
Ok perfect ! 👍🏻 

It's works fine! I just have to put `/slack` at the end of the Discord webhook.

I just see this warning about `content` key but it's not a real problem for me 😬:
![image](https://user-images.githubusercontent.com/36677774/201494051-1c1304ee-ec2f-4aab-afb2-47200fa23a74.png)

It is possible to add a note in the readme about slack webhook like . ;-)

**Comment by NHAS** [comment]
Honestly, I think your suggestions are good ones which I may include in the future if I can find the time! 

I will update the docs as well.
