### ISSUE TITLE
The software does not work if there are spaces in the path.

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#76]
If you put the windows build in a folder with gaps in it, the software does not start. ( I haven't tested Linux )

**Comment by NHAS** [comment]
Hi there! 

Thanks for this, I'll investigate it in the next couple days and send out a fix. Sorry about that super annoying, do you happen to be able to give me some more details about where and what you're trying to run it on? 

(i.e, windows version, specific file path, rssh version)

**Comment by chikamobina** [comment]
Any version of WIndows, I ran it on 2019 server, and I only run it on windows server.

Any path with a space, for example I did C:\ProgramData\Package Cache\revssh.exe

**Comment by NHAS** [comment]
Alright interesting, have you tried running the program with the `--foreground` flag? 

E.g

`revssh.exe --foreground <your.rssh.server.here>`

**Comment by chikamobina** [comment]
Haven't tried it.

**Comment by NHAS** [comment]
Cool I can replicate this :)

**Comment by chikamobina** [comment]
Great, waiting for a correction)

**Comment by NHAS** [comment]
Sweet as, its now on the unstable branch if you want to pull and test that directly. I've tested it myself, but just wanna make sure.

**Comment by chikamobina** [comment]
Yeah, everything seems to be fine. Thank you.

**Comment by chikamobina** [comment]
Can I ask you a question about garble here? I successfully install the version you gave me, specify the path, but still no link to garble

**Comment by NHAS** [comment]
I'd prefer if you opened that as a new issue so folk can search it if they need. Plus give me some more details about your setup :)
E.g give me your PATH, how you installed garble etc

**Comment by chikamobina** [comment]
Okay, I'll do it later.
