### ISSUE TITLE
RSSH Client password restriction

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#78]
Hi DR,
Can the rssh clients require a password before a user who connects to the server can run commands/copy files/etc on them?

**Comment by NHAS** [comment]
Sorry I dont see how this would add anything to the project. 

Are you meaning that people would be able to use SSO to log in to RSSH server to manage its clients? Or are you meaning that the controlled clients use password authentication rather than key based authentication?

**Comment by shanjunmei** [comment]
Assign a user name and password to each device, and compile a dedicated client, so that the identity of each connected device can be identified

**Comment by shanjunmei** [comment]
The value is that it can be turned into a commercial project, not just a hacker tool,such as manage Iot device

**Comment by NHAS** [comment]
> Assign a user name and password to each device, and compile a dedicated client, so that the identity of each connected device can be identified

As it stands each client is issued its own public private key pair when using the webserver `--link` command. This is more than enough to uniquely identify each device (and is in-fat more robust than a username+password based system anyway). 
 

> The value is that it can be turned into a commercial project, not just a hacker tool,such as manage Iot device

I suppose I'll be seeing monetary benefit from this then? 
Are you proposing that you sponsor this feature and give me the revenue that you'll be making from it?

**Comment by shanjunmei** [comment]
yes, each device has a password baked in that you would have to supply in order to access the device

**Comment by NHAS** [comment]
So how are you planning on sponsoring this feature? If you plan on using RSSH as a commercial project.

**Comment by shanjunmei** [comment]
Maybe I can't sponsor you directly, but I think this is a direction, if it is just a hacking tool, I think it will be more difficult to get sponsor.just a suggestion，never mind whether you want to achieve it depends on your will

**Comment by NHAS** [comment]
I personally don't believe that being "just a hacking tool" is an accurate description of this project, nor do I believe including your desired feature would make it any less a "hacking tool". 

In terms of gaining sponsors. The major limitation of that isn't your perception of the project, it's mainly that open source solutions are not where the money's at, even less those that are BSD-3-Clause licensed. 

I think the feature of having clients require a password is a good one. However in the context of 'commercializing' it leaves the feeling that it wont be me that makes any money out of it. 

So I think for now I'll say, if you want it, you can create it, I'll put this on the back burner.

**Comment by shanjunmei** [comment]
thanks ,just share the idea
