### ISSUE TITLE
Issues in exec

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#80]
To track the issue, per our discussion, bugs are:

- `runCommandWithPty` neglects to add a space, so `foo -bar -baz` becomes `foo-bar -baz`. Current workaround is to execute `f oo -bar -baz` and the command becomes sane again, as the first space gets yote. Easy fix, just need to append a space between the command and args.
- `runCommand` treats argv poorly... perhaps? Needs more investigation, but I'm concerned that `powershell -c "foo bar"` would lead to an argv of `["powershell", "-c", "\"foo", "bar\""]` whereas it should be `["powershell", "-c", "\"foo bar\""]`... right?
- Dangling pointer [here](https://github.com/NHAS/reverse_ssh/blob/9e48a0f1392ee8b8261222b27d75bd5defbcdb46/internal/client/handlers/session.go#L82) leads to it following the wrong code path is a pty has been attached to this client before.

**Comment by NHAS** [comment]
For your second point I've just been testing it and powershell doesnt seem to care? Which is kind of wild, however other shells definitely do, which is quite frustrating haha.

**Comment by NHAS** [comment]
These issues should now be fixed
