### ISSUE TITLE
Powershell highlighting makes some text invisible

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#81]
Certain text gets highlighted weirdly and becomes inviisble.

Typing `powershell -exec bypass` shows this:
<img width="442" alt="Screen Shot 2022-12-21 at 11 15 50 AM" src="https://user-images.githubusercontent.com/4683714/208777325-2625a352-fe0e-401a-82fc-2591ea5f1bcc.png">

Highlighting with my cursor shows the text is there, its just the same colour as the bg:
<img width="527" alt="Screen Shot 2022-12-21 at 11 16 10 AM" src="https://user-images.githubusercontent.com/4683714/208777383-0b9b01fb-248b-4fb8-b903-a102d6aa70d2.png">

**Comment by NHAS** [comment]
Im fairly certain this is because the powershell output expects the background to be blue, so mildly dies the death. I can solve this by starting the powershell instance in a cmd instance, or by setting the background manually I believe.

**Comment by NHAS** [comment]
Weirdly enough this actually shows fine on terminal screen

**Comment by NHAS** [comment]
Unfortunately this seems to be a limitation of conpty, it refuses to have its background set :(
