### ISSUE TITLE
Allow clients to be identified by key comment

### ISSUE THREAD

**Issue by lachlan2k** [NHAS/reverse_ssh#83]
It would be a cool feature idea to leverage the ssh "comment" field in `authorized_controllee_keys` to identify clients.

For clarity, the SSH comment field is the string after the key material, specified in the `-C` argument to `ssh-keygen`. I.e.
```
$  ssh-keygen -C 'foo bar' -t ed25519
Generating public/private ed25519 key pair.
Enter file in which to save the key (...): /tmp/test
...
$ cat /tmp/test.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH9vRi33xryjFf63mmQhjMIkPxxPtpxBtVNBl4xitU5K foo bar
```

"foo bar" in this case is the "comment".

I propose that in `ls` and `ls -t`, if there is a comment field present in the `authorized_controllee_keys` entry, it should display it in-place of the public key hash.

Ontop of this, I think the `link` command should also allow `-C`, similar to ssh-keygen. I.e. `link -c "my boi"`, then, when the newly generated key is created, it should include this comment.

**Comment by NHAS** [comment]
Ahhhhhh thats a fantastic idea, thank you for this. I'll add this after doing the powershell colors.

**Comment by NHAS** [comment]
This is now on unstable
