### ISSUE TITLE
--insecure doesn't work

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#84]
Hi, I was working on the last version, I decided to upgrade because you added cool fixes, but I forgot to move the rssh key and deleted it, I start the new rssh version with the --insecure key, supposedly the old clients should connect, but they do not, they just spam to my server. 
Failed to handshake (read tcp IP_RSSH:443->IP_CLIENT:54798: read: connection reset by peer)

And the ls -t command doesn't work with --insecure enabled

ssh IP_RSSH -p 443 ls -t
channel 0: open failed: unknown channel type: unsupported channel type: session

**Comment by NHAS** [comment]
Ah yes, the most recent changes are rather important as they fix a rather bad bug. 

Im going to assume that you generated the said client with the `link` command? If so unfortunately the client is using mutual authentication and is checking the server key as well, so if you deleted the server ssh private key it'll be checking the public component and not allowing connection. 

`--insecure` is a purely server side "is this client in my authorised controllee keys list" flag, although I understand how that is very unclear.

**Comment by chikamobina** [comment]
Oh, I got it, thanks.
