### ISSUE TITLE
Can't use garble in link

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#85]
Hi again, I can't get garble to work in the link.
/root/go/bin/garble it is installed here, my $PATH 

"/root/go/bin/garble/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/bin:/bin/go:/bin/go:$/root/go/bin"

What am I doing wrong? Can you send me the right command to add to $PATH ?

**Comment by NHAS** [comment]
Assuming you're running the RSSH server as root, you can set your path like this.

```bash
# Note the :
export PATH=/root/go/bin:$PATH
```

The linux `PATH` is a series of directories that the shell searches for executables. It seems that you've both missed the `:` and set the PATH directory to be the `garble` file directly here `"/root/go/bin/garble/usr/local/sbin...`

**Comment by NHAS** [comment]
As this isnt really an RSSH issue/bug Im going to close this issue. Hope that helps!
