### ISSUE TITLE
Point out your wallets on the home page

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#86]
I think you should specify your wallets cryptocurrencies on the main page, I for example want to support you and I think not one, if you do not want to indicate the main page, then indicate it here.

**Comment by NHAS** [comment]
Thank you! You're very generous, I dont have any wallets currently alive, I just set up a Kofi if you're comfortable with donating there, otherwise I'd be more than happy to take recommendations on what wallet you'd support (Im always in favor of monero)

**Comment by NHAS** [comment]
Here is my monero receive address! Hopefully I did it all right :P 

`8A8TRqsBKpMMabvt5RxMhCFWcuCSZqGV5L849XQndZB4bcbgkenH8KWJUXinYbF6ySGBznLsunrd1WA8YNPiejGp3FFfPND`

**Comment by chikamobina** [comment]
Give BTC plz)

**Comment by NHAS** [comment]
Sweet! Here you go:
`bc1qm9e9sfrm7l7tnq982nrm6khnsfdlay07h0dxfr`

**Comment by NHAS** [comment]
I've added these to the readme as well, so I'm going to close this issue. 

Thanks again!

**Comment by chikamobina** [comment]
Sent it, thank you.

**Comment by NHAS** [comment]
Thank you!

**Comment by NHAS** [comment]
WOW! Thank you so much you've very generous

**Comment by chikamobina** [comment]
Very cool project, continue)

**Comment by NHAS** [comment]
Will do!
