### ISSUE TITLE
[invalid did not confirm issue] connectBackAddress always be overwrite by listenAddress

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#88]
connectBackAddress always be overwrite by listenAddress

**Comment by NHAS** [comment]
What? I need more information on this.

If you're referring to the server main, connectBackAddress will be overwritten by listenAddress when `--external_address` is not specified?

Which is how it's suppose to be

**Comment by shanjunmei** [comment]
`	webserver := options.IsSet("webserver")
	connectBackAddress, err := options.GetArgString("external_address")

	if err != nil && webserver {

		_connectBackAddress = listenAddress_

		//Special case where we're using :3232 as an example, which listens on all interfaces
		//However we need to have a valid address for the link command, so we get the first interface
		addressParts := strings.Split(listenAddress, ":")
		if len(addressParts) > 0 && len(addressParts[0]) == 0 {

			port := addressParts[1]

			ifaces, err := net.Interfaces()
			if err == nil {
				for _, i := range ifaces {

					addrs, err := i.Addrs()
					if err != nil {
						continue
					}

					if len(addrs) == 0 {
						continue
					}

					if i.Flags&net.FlagLoopback == 0 {
						**_connectBackAddress = strings.Split(addrs[0].String(), "/")[0] + ":" + port_**
						break
					}
				}
			}
		}

	}
`

**Comment by shanjunmei** [comment]
> ` webserver := options.IsSet("webserver") connectBackAddress, err := options.GetArgString("external_address")
> 
> ```
> if err != nil && webserver {
> 
> 	connectBackAddress = listenAddress
> 
> 	//Special case where we're using :3232 as an example, which listens on all interfaces
> 	//However we need to have a valid address for the link command, so we get the first interface
> 	addressParts := strings.Split(listenAddress, ":")
> 	if len(addressParts) > 0 && len(addressParts[0]) == 0 {
> 
> 		port := addressParts[1]
> 
> 		ifaces, err := net.Interfaces()
> 		if err == nil {
> 			for _, i := range ifaces {
> 
> 				addrs, err := i.Addrs()
> 				if err != nil {
> 					continue
> 				}
> 
> 				if len(addrs) == 0 {
> 					continue
> 				}
> 
> 				if i.Flags&net.FlagLoopback == 0 {
> 					connectBackAddress = strings.Split(addrs[0].String(), "/")[0] + ":" + port
> 					break
> 				}
> 			}
> 		}
> 	}
> 
> }
> ```
> 
> `

we try search by `connectBackAddress =`  can found there are two rewriting connectBackAddress in this code

**Comment by NHAS** [comment]
The code you've highlighted does not cause the connect back address to always be set to listenAddress.

The if statement checks for an error, that error indicates if the argument `--external_address` was specified. If it was, then it omits that whole block?

**Comment by shanjunmei** [comment]
> The code you've highlighted does not cause the connect back address to always be set to listenAddress.
> 
> The if statement checks for an error, that error indicates if the argument `--external_address` was specified. If it was, then it omits that whole block.
> 
> Have you tried using `--external_address` or are you purely reading the code?

Sorry, my bad, just read the code, didn't actually test it

**Comment by NHAS** [comment]
Please don't open issues without verifying that what you're talking about is actual issue.

It wastes my time and makes me less open to seriously considering your issues in the future.
