### ISSUE TITLE
The process opened by the client does not exit correctly in some scenarios

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#89]
currently connected from the server to the client, after opening a terminal, if you actively execute the exit command, the terminal process opened by the client can also be closed normally, but if you directly close the entire session, the client will accumulate more and more multiple terminal processes

**Comment by NHAS** [comment]
Please give an exact set of steps to replicate this issue.

**Comment by shanjunmei** [comment]
os :Win10
steps 1: run server
step 2: run client
step 3: check client process tree
step 4: open a test terminal
step 5: ssh to sever thru test terminal
step 6:connect to client thru test terminal
step 7:  check client process tree
step 8: close test terminal directly
step 9:check client process tree

compare the result of step 3,7,9 should can found the issue

**Comment by NHAS** [comment]
Ah yes. I thought this bug had been fixed a while ago, funny that it's still showing up.

Do you have the same problem on linux?

**Comment by shanjunmei** [comment]
> Ah yes. I thought this bug had been fixed a while ago, funny that it's still showing up.
> 
> Do you have the same problem on linux?

yes ，same issue found in Linux （Ubuntu 22.04）

**Comment by shanjunmei** [comment]
> > Ah yes. I thought this bug had been fixed a while ago, funny that it's still showing up.
> > Do you have the same problem on linux?
> 
> yes ，same issue found in Linux （Ubuntu 22.04）

Sorry, maybe I read it wrong, repeated verification later, didn't find it.pls ignore it

**Comment by NHAS** [comment]
Didn't it on linux or at all?

**Comment by NHAS** [comment]
This is now live on the unstable branch. I've given it a test and can confirm it no longer exists. I'll close this when you've confirmed its gone, or when it is released into main.

**Comment by shanjunmei** [comment]
tested ,work fine
