### ISSUE TITLE
ask some questions

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#92]
Hello, I am learning the principle of reverse ssh in your code and jumping to the target server through the rssh service.

Because I am not familiar with the go language, I do not understand the principle after viewing the source code. My current understanding is that the rssh client will actively initiate a tcp connection to the rssh service port 3232, and the rssh server listens to port 3232 after receiving the connection. Generate a random id to record this reverse ssh tunnel. The attacker specifies the id to connect to the rssh server through the ssh -J parameter. The rssh server will query the corresponding ssh tunnel and jump to the target host according to the id. I don’t know if my understanding is correct.

I currently have a need for python programming. I want to use the paramiko library to obtain a session that jumps to the target host ssh as a programming interface. How can I connect to the rssh server and then continue to connect to the target machine? How to restore the parameter(-J) id to host and port?

**Comment by NHAS** [comment]
Hi there! 
This is a really great beginner question so I'll try and clarify what I think your questions are.   
  
First and foremost everything in the RSSH project complies with the SSH standard, so all the standard tooling and most of the RFCs for SSH apply to RSSH. I.e it might be a good idea to go and have a read of how ssh works to kind of wrap your head around what the RSSH client and server are actually doing (I also have a blog post coming out soon that I'll link here to help perhaps).  
  
 > the rssh client will actively initiate a tcp connection to the rssh service port 3232
   
 Yep this is totally correct! The server will generate a random ID, and record the hostname, connecting IP address and public key hash all as IDs.  
   
 >  The attacker specifies the id to connect to the rssh server through the ssh -J parameter
   
Almost correct. The `-J` or "`jump`" flag actually specifies what server you want to connect to *before* you connect to your target machine.   
In this instance the `-J` parameter is actually your rssh server *not* the client. 
E.g 

```sh
ssh -J your.rssh.server:3232 <target_id>
```

>  I want to use the paramiko library to obtain a session...
Unfortunately I dont do a lot of python programming. But this gist (https://gist.github.com/tintoy/443c42ea3865680cd624039c4bb46219) may help you as it showcases using the SSH protocol jump host directive (called `direct-tcpip`). 

This is a little less low level: https://github.com/paramiko/paramiko/issues/1018#issuecomment-744151656


Hope that helps!

**Comment by tdragon6** [comment]
Thank you very much for your enthusiastic answer and look forward to your blog. In the link you shared with me, I seem to have found a higher-level library fabric than paramiko, which can more conveniently fulfill my needs and jump through gatway.

 I still have a little doubt that I can use my rssh address and port (for example: 3232) to identify the connection for the hostname of the rssh server. For the target host, can I directly use the corresponding target id to mark it? Just like using native commands line.`ssh -J your.rssh.server:3232 <target_id> `

**Comment by NHAS** [comment]
Yes, so any of the identifiers given from the output of `ls` in rssh can be used to connect to a target. 
Unique ID is best if you'll be running multiple agents on the same host with the same public keypair.

**Comment by tdragon6** [comment]
Thank you so much, I successfully obtained the session interface of the target host through python paramiko. In the future, I will publish a B/S architecture program based on your rssh project on my github. In the web page, you can execute the shell of the target host and manage files. Welcome to use and make suggestions when I release！

Now I have another question, the id can uniquely identify a direct-tcpip session, if I use the host name + port, is it also unique? I think so.

**Comment by NHAS** [comment]
The hostname may not be unique. Obviously hosts may have the same hostname, or you may run multiple rssh clients on the same host.

When jumping through the rssh server you should not specify a port on the remote target as technically no port is actually opened by the rssh client.
Just use one of the identifiers.


If you try and jump to with an identifier that stands for multiple hosts you'll get an error message.
