### ISSUE TITLE
Exit abnormally, causing reconnection to fail

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#93]
https://github.com/NHAS/reverse_ssh/blob/205463ba31736d91cd024a8d12f773d18048fc57/internal/client/client.go#L151

As in the title, this line of log will cause the client to exit abnormally in some cases, instead of trying to reconnect again. If the connection destination is a domain name, the connection may be permanently lost due to the temporary resolution failure of the domain name, or because the client network restarts, cause permanent loss

**Comment by NHAS** [comment]
Hi there!

I think this is a valid bug. 

It was an attempt to fix an issue where an invalid hostname/ip was baked in to a binary so the binary would just stay trying to connect to nothing indefinitely.

But I think it's just ended up making it non functional. I'll remove the clause for unknown host but keep the missing port failure. 


Thanks

**Comment by NHAS** [comment]
This is now on the unstable branch. I have had to remove the `tun` device mechanisms due to build problems (as the library it was relying on has changed and broken it for my go version). 
So just be a aware of that.
