### ISSUE TITLE
Is the timeout period too long?

### ISSUE THREAD

**Issue by shanjunmei** [NHAS/reverse_ssh#94]
https://github.com/NHAS/reverse_ssh/blob/205463ba31736d91cd024a8d12f773d18048fc57/internal/client/client.go#L48
https://github.com/NHAS/reverse_ssh/blob/205463ba31736d91cd024a8d12f773d18048fc57/internal/client/client.go#L93
https://github.com/NHAS/reverse_ssh/blob/205463ba31736d91cd024a8d12f773d18048fc57/pkg/mux/multiplexer.go#L181

During the test, it was found that after the client computer was directly disconnected from the network, the client did not find the abnormality in time. Using the network detection tool, it was found that its status was still connected to the server, but the server showed that the client was offline, even though the client The client network is reconnected, and even if the client machine recovers the network connection, the reverse ssh client will no longer be able to go online

**Comment by shanjunmei** [comment]
Test environment, the server runs on linux, and the client runs on windows11

**Comment by NHAS** [comment]
Funny enough I've also found that the client does this same thing you're referencing here and have been meaning to fix it (have been a tad busy).


This is definitely very frustrating. For context this was added as a user was using rssh for remote iot devices where even keepalives would have costed more money to transmit.
I think in hindsight while it's good to have the option to turn them down, or off, it's not appropriate everywhere.

I'll change this. Thanks

**Comment by NHAS** [comment]
For the multiplexer on the server side, that default code is not used. The default timeout is 5 seconds-ish by default and is enforced by a timeout mechanism thats above the TCP layer. So this is really a client side sort of thing.

**Comment by NHAS** [comment]
Hey this lives on the unstable branch now. What I've done is make the server keepalives contain the current server timeout (which is configurable), the client rssh binary then sets its connection read and write deadlines to the server deadline * 2 in seconds.

As a keepalive is issued every `n` number of seconds, the read deadlines should never expire if the connection is up. 
Im going to keep the TcpKeepAlives set to 2 hours. As they become superfluous with this scheme, and it just means that the server owner can configure the timeouts to be whatever they want it to be. 


Please check that it fixes this issue, then I'll make a release for your two bugs. Thanks
