### ISSUE TITLE
Add client OS architecture

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#95]
Is it possible to add the operating system architecture information of the connecting client in ls and webhook?

**Comment by NHAS** [comment]
You're going to think Im an idiot. But that never even crossed my mind. Yes of course I can add that and am annoyed at myself for not doing so earlier.

**Comment by tdragon6** [comment]
Thanks, looking forward to your new release! Because this function is needed in the project I develop!

**Comment by NHAS** [comment]
This is now on the unstable branch please check it out and then I'll do a release.

**Comment by NHAS** [comment]
Example format: 

```sh
catcher$ ls
834f090292ef057a662ce7d4db672ffc7b1b2fe7 26efe5d48d08c519362e62ad7899e21a030b2179 nhas.test-machine 10.0.0.14:34648, version: SSH-v1.0.14-3-g99d7ed8 arch: linux_amd64
```

**Comment by tdragon6** [comment]
The operating system information exists in ls, but it is not added in webhook.

**Comment by NHAS** [comment]
Oops yep totally forgot to do that. Sorry!

**Comment by NHAS** [comment]
Sweet, I've added it to the ClientVersion in ssh. Which is a bit more robust than what I was doing before. Does mean that you'll have to parse the version string which is now in the following format: 

```sh
catcher$ ls
b9353e57f542e76ff144989edb951fa08e9d8bf7 4b1d7bf85c633b3bb2c14be5554456745318887a nhas.test-machine 10.0.0.14:45712, version: SSH-v1.0.14-4-g411921e-linux_amd64
```

Webhook:
```json
{"Full":"{\"Status\":\"connected\",\"ID\":\"5c75978a7418f40c38f215c95bf4a551cf5318f9\",\"IP\":\"10.0.0.14:48192\",\"HostName\":\"nhas.dkowhan\",\"Version\":\"SSH-v1.0.14-4-g411921e-linux_amd64\",\"Timestamp\":\"2023-02-23T08:03:55.158264245+13:00\"}","text":"nhas.dkowhan (5c75978a7418f40c38f215c95bf4a551cf5318f9) SSH-v1.0.14-4-g411921e-linux_amd64 connected"}
```

**Comment by tdragon6** [comment]
Nice! Thanks! If there are no other problems, it can be merged into the mainline branch.

**Comment by tdragon6** [comment]
Sorry, it just occurred to me, if it's convenient:
1. In the `webhook`, separate the user name of the client from the host name, and add a new user name field.
2. Increase the connection time of the client in `ls`.

**Comment by NHAS** [comment]
Adding the seperate fields for username and hostname is a bit of a pain to be honest with you. I'd prefer to leave then as is, it's fairly easy to split it by the first dot.

I'm not sure what you mean by increase connection time with ls.
