### ISSUE TITLE
About authorized keys

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#96]
I have another question. Both the connection server and the reverse connection server use a public-private key pair. Can I compile the project like this:

 1. make server 
 
2. Generate a pair of public and private key pairs by myself as the key to control the rssh server, put the pub in ~/.ssh, and put the priv named authorized_keys in the bin.

3.  Generate a pair of public-private key pairs by myself as the key for the reverse connection of the client to rssh server. The pub is named authorized_controllee_keys, and the priv is named id_ed25519. Put these two in the bin. 

4.Start the server and use the link to generate the client. Can the client connect to the server in reverse? Is this the same as directly compiling everything?

**Comment by NHAS** [comment]
Not entirely certain what you mean. What are you trying to accomplish? 

The `link` command on the server always regenerates a new public keypair. Compiling with `make` gives you the option to either generate a new keypair for the client or not.

**Comment by tdragon6** [comment]
I just re-read the source code and readme, and now I understand. After I generate a public-private key pair as the key to connect to the rssh server, I name the pub authorized_keys as the credential for connecting to ssh, just like a normal ssh connection. At the same time, I can name the priv as id_ed25519 as the fingerprint source of the rssh server. It can also be used as a key to connect to the rssh server.

 After using the link to generate the client, the client will contain the rssh server fingerprint and its newly generated private key, and at the same time write the public key into the authorized_controllee_keys file. When the client connects in reverse, it will verify the key pair and fingerprint at the same time, and only if all pass connect. 

So if I transplant the project or recompile the server, when restarting the server, I only need to ensure that the authorized_keys, id_ed25591 and authorized_controllee_keys are the same as before, and I can continue to receive the reverse connection from the previous client, and I can use the private key id_ed25591 to log in rssh-server. 

Is my understanding correct?

**Comment by NHAS** [comment]
Almost. The id_ed25519 that the server generates is the servers private key.
You should not be using the id_ed25519 that the server generates as you access to the server. 


Ideally you should put your own public key, that you've generated with ssh-keygen into the authorised_keys file on the server.
As the rssh server works exactly like a regular ssh server.

**Comment by NHAS** [comment]
If you copy all the things you've copied youll be able to receive connections.
