### ISSUE TITLE
sftp upload file problem

### ISSUE THREAD

**Issue by tdragon6** [NHAS/reverse_ssh#98]
Hi, when I use the sftp command to upload files, I find that it will take up a lot of connection resources with the target, causing the ssh connection and other sftp operations to be extremely slow at this time.

Is there a way to solve this problem?

**Comment by tdragon6** [comment]
Also sometimes results in disconnection from the target host.

**Comment by NHAS** [comment]
Howdy, that's very odd I haven't had that issue.

Can you give me more details?

What version of rssh are you using?

Is the high resource usage on the target side or on your side?

Do you have client or server logs when a disconnection happens?


And finally how big are the resources you're moving?

**Comment by tdragon6** [comment]
This problem exists when using sftp to transfer any file size. I tested that the size of the transfer is about 50MB. The specific operation is as follows: 

1. sftp -J RsshIP:3232 SessionID

2. sftp>put /LocalFile

3. At this time, sftp is transferring data.

4.  At this time, using ssh -J or sftp -J to establish an additional connection with the target will be very slow and the operation after the connection will be delayed.

**Comment by NHAS** [comment]
Hmmm. So, the rssh client starts the aftp handler in a different thread. I think you might be running into bandwidth issues there?


I'll give it a test on my local network and see if I can replicate. The sftp stuff gets passed off to a library however.

**Comment by NHAS** [comment]
So unfortunately I cant replicate this behavior on my machine. 
What might be happening in your case is the CPU usage spikes dramatically when you use sftp/scp (and is unfortunately outside of my control) and this may cause the host machine to become unresponsive. 

I tried by uploading and downloading a 2GB file, and the box did spike to using 99% cpu. But thats all I can see, no disconnections or slowness in connecting to the machine during the copy op. 

If you have any more information or logs around the issue I'd be happy to reopen then issue :)
