### ISSUE TITLE
service for .dll

### ISSUE THREAD

**Issue by chikamobina** [NHAS/reverse_ssh#99]
Hi, it would be great if -s service --install worked for .dll files.

Or if it doesn't go into the logic of the application, you could declare it as a windows service, so I could run it as a service myself manually via sc.exe.

At the moment when I start it via sc.exe, the file starts and works, but about 1 minute, then the windows service, itself turns it off, because it does not respond that it is running.

I solved this problem long time ago in my software, you just have to let windows know it's a service and that it's running, I think it's this https://github.com/judwhite/go-svc, but you did it for .exe, so I think you know, I don't have to teach you.

Thanks a lot for your development, it would be cool if the .dll would run as a service.

**Comment by NHAS** [comment]
Hi there.

Thanks for editing this to be in English!
I haven't thought about the dll side of things in quite some time.


I'd be more than happy to make it run as a service (I thought I already had).

**Comment by NHAS** [comment]
This is on unstable branch, please test it out

**Comment by chikamobina** [comment]
Thank you very much)

**Comment by chikamobina** [comment]
And it gives an error, but the service is created and even seems to work

**Comment by chikamobina** [comment]
No, through this command he made a simple service, with this way C:\Windows\system32\rundll32.exe, So you only have to do it yourself by hand via sc.exe?

**Comment by NHAS** [comment]
Yeah I havent tested it with the `service` subsystem. If it works with rundll32 then Im happy with it, so does that work?

**Comment by NHAS** [comment]
Unfortunately installing via the submodule would mena having to detect if the rssh client was a shared object or not.
As the current module just installs it directly, I.e it doesn't add rundll into the path.

I'll make a warning to tell people that in the module. (or I could be not lazy and actually add the rundll to the path which shouldn't be awful
